### ISSUE TITLE
Error installing 'bootnet': "undefined exports: centralityCompare"

### ISSUE THREAD

**Issue by cmg212** [SachaEpskamp/bootnet#1]
Dear Sacha, 

I am having trouble installing bootnet from the Github repository. I receive the error:

`Error in namespaceExport(ns, exports) : 
  undefined exports: centralityCompare
Error: loading failed
Execution halted`

I am running:

`install_github("SachaEpskamp/bootnet")`

I see that you have been recently updating the package, including a renaming of the centralityCompare() function. 

Best
Conor Goold

**Comment by SachaEpskamp** [comment]
Thanks! I see that I forgot to update the NAMESPACE file. I have recently made many changes to the bootnet package and incorporated new methods for testing differences between centrality measures and quantifying the stability of results. I'll have a new version of the paper ready probably next week describing this new functionality (I expect it to be online by the end of the month, but can send a draft if you are interested). It could be that the developmental bootnet version has some bugs still as I haven't thoroughly tested yet. Please let me know if you run into any problems!

**Comment by cmg212** [comment]
That's great! It installs successfully now. I'd certainly be interested in seeing the draft if you are happy to share. 
Conor
