### ISSUE TITLE
Follow-up on #83 re. `R CMD check`

### ISSUE THREAD

**Issue by mihaiconstantin** [SachaEpskamp/bootnet#100]
Hi Sacha,

I already commented on #83, but since that PR is closed, I am also adding my message here for clarity.

> Hi Sacha,
>
> Ah, the workflows have been updated in the meantime. Let me send another PR with the corresponding updates!
>
> About what it does, the idea is that every time you merge/ commit to the `main` or `master` branch, it runs the `R CMD check --as-cran` on three operating systems and three versions of `R` I think (i.e., old release, release, and the development branch). It can be handy to catch things before the `CRAN` team...
>
> For public repositories, you have a certain number of run minutes (i.e., 3000 I believe), but if you associate your .edu address with GitHub (i.e., [this page](https://education.github.com/pack)), you essentially have unlimited run times.
>
> I'll follow up shortly with the updated workflows!
>
> Best,
> Mihai

**Comment by SachaEpskamp** [comment]
Thanks! I saw it!
