### ISSUE TITLE
Error in estimating Network using "IsingFit"

### ISSUE THREAD

**Issue by moritzpers** [SachaEpskamp/bootnet#104]
Hi,

I use a simple input matrix with four variables and 500 observations with 1 or 0. Everytime I try the code estimateNetwork(data, "IsingFit"), there is a problem with the argument 'x'. If i use the dataset with "IsingFit" (from the IsingFit package), I get an acurate network, but with estimateNetwork() there is always an error. I want to use estimateNetwork() to compute the network accuracy and stability, which is -as far as I know - not possible with the IsingFit-package only.

my code: 
> # Ising model:
Network <- estimateNetwork(data, "IsingFit") Estimating Network. Using package::function:   - IsingFit::IsingFit for network computation     - Using glmnet::glmnet Error in h(simpleError(msg, call)) :    error in evaluating the argument 'x' in selecting a method for function 'drop': non-conformable arguments

**Comment by SachaEpskamp** [comment]
Hi! I cannot answer this question without seeing the data. Perhaps the class of the data is in an unexpected form? Did you try to convert to data frame first using `as.data.frame(data)`?

**Comment by moritzpers** [comment]
First, I converted the .sav input file to a dataframe, but the error remained. Later I started to use a csv. file as input and checked the variable types and classes (which were already integer/numeric) - then it worked somehow.

Thanks anyway!
