### ISSUE TITLE
How to deal with nested data?

### ISSUE THREAD

**Issue by 000Annemarie** [SachaEpskamp/bootnet#105]
Dear dr Epskamp,

Could you advise me on how to deal with nested data? 
I have estimated a psychological network using data from 2946 respondents out of 23 different groups (i.e. churches). Although the groups are not the focus of my research, I want to control for possible clustering effects in my network. Are there ways to deal with nested data in the bootnet/estimateNetwork package? 

I appreciate any help you can provide.

**Comment by SachaEpskamp** [comment]
Hi Annemarie,

I am afraid that there is not currently a default set implemented in bootnet that will estimate a multi-level model controlling for such clustering...

Best,
Sacha
