### ISSUE TITLE
About model select & difference between cor and cor_auto in ggmmodselect/thresholded EBICglasso

### ISSUE THREAD

**Issue by Brooks0303** [SachaEpskamp/bootnet#107]
Hi Mr.Epskamp,
I am a new hand in PNA having some questions. Please help me. Thanks a lot!
My data constructed by some parts which have different sample size from 2000 to 10000+
So I follow the suggestion in _New features in qgraph 1.5_ ,use ggmmodselect and thresholded EBICglasso algorithm to create the net.

There's my questions,
1. If I want to compare the net in these different parts, should I use the same algorithm(ggmmodselect and thresholded EBICglasso) in all the sample, even the sample size is only 1000-2000?  OR I should use the dufault EBICglasso in estimatenetwork function for the small one, ggmmodselect for the big one. OR use default EBICglasso for all the sample? 

2. When I use ggmmodselect and thresholded EBICglasso as [qgraph1.5 tutorial](http://psychosystems.org/qgraph_1.5) doing.

`qgraph(cor_auto(data), graph = "glasso",sampleSize = nrow(data), threshold = TRUE, layout = "spring", theme = "colorblind",title = "Thresholded EBICglasso", cut = 0,groups = groups)`  or  `ggmModSelect(cor_auto(data), xxxxx)`

the small sample's analysis will report the ERROR :'S' is not positive definite
but when I change code to `cor(data)` or just use the default estimatenetwork function, same sample wont show the ERROR
and I check the latter update [in psychonetrics](http://psychonetrics.org/2020/05/13/bootnet-version-1-4/), it seems that cor is more suggested than cor_auto

So Id like to know Whats difference between cor and cor_auto in ggmmodselect/thresholded EBICglasso. can I replace all the cor_auto 
by cor in all sample no matter big or small？

THX again for your kind help!!!

**Comment by Brooks0303** [comment]
here's the reference link 
http://psychosystems.org/qgraph_1.5
http://psychonetrics.org/2020/05/13/bootnet-version-1-4/

**Comment by SachaEpskamp** [comment]
Hi! These are two very outdated blog posts so you might not want to rely on these too much. As for the choise of estimator we wrote this paper:

https://psycnet.apa.org/record/2022-06515-001

And another useful paper might be:

https://psycnet.apa.org/record/2022-52634-001

If you want to compare samples the estimator ideally is the same, and it is best to use something like a multi-group analysis or permutation test (e.g., NetworkComparisonTest). Also, I don't recommend using the threshold in EBICglasso anymore nor do I recommend using polychoric correlations as input (see above paper for simulations showing this doesn't work very well). 

The best updated recommendations can be found in our new textbook:

https://www.routledge.com/Network-Psychometrics-with-R-A-Guide-for-Behavioral-and-Social-Scientists/Isvoranu-Epskamp-Waldorp-Borsboom/p/book/9780367612948

**Comment by Brooks0303** [comment]
GET IT! 
THX for your reply. Ill read these papers and book to find more suggestion.
And thanks in advance if there are more confusion😀
