### ISSUE TITLE
How to adjust the size of labels

### ISSUE THREAD

**Issue by GangYLu** [SachaEpskamp/bootnet#108]
Hi Dr. Epskamp

When I wanted to plot the result of bootstrapped confidence intervals of estimated edge-weights. I ran into a small issue. The labels of each edge were too big so that they overlapped with each other. Could you give me some advice how to adjust the size of labels?

Here is my code:
boot1 <- bootnet(network_whole, statistics = c("edge", "strength", "bridgeStrength"), 
                       communities = community_structure, nBoots = 2500, nCores = 8)

plot(boot1, order = "sample") 

I also attached a pdf file which is the plot I mentioned above.
[accuracy result.pdf](https://github.com/SachaEpskamp/bootnet/files/12194015/accuracy.result.pdf)

Thank you for your time,

Lu Gangyuan

**Comment by SachaEpskamp** [comment]
Hi! The output from `plot(boot1, order = "sample")` is just a ggplot2 object you can further change. For example, you can change the style with `+ theme(...)` using ggplot2 commands. Another option is simply to store the figure in a big enough PDF file:
```
pdf("bootstraps.pdf", height = 20, width = 10)
plot(boot1, order = "sample")
dev.off()

```

**Comment by GangYLu** [comment]
Thanks for your help, Dr. Epskamp. Best and sincere wishes.
