### ISSUE TITLE
Similar question to "Plotting centrality stability showing only "strength" #88"

### ISSUE THREAD

**Issue by dengxuebin** [SachaEpskamp/bootnet#109]
Hi SachaEpskamp, my code is following, but the problem was not changed, still only "strength" although according to your answer "use the statistics argument in bootnet(...) as well.". I am very confused. Hope your reply. Thanks a lot !

network <- estimateNetwork(as.matrix(dat2), default = "mgm",
                           type = type1,
                           level = level1)
#(3)case-dropping bootstrap
b1c <-bootnet(network,nBoots=100,nCores=8,
              type="case",statistics=c("strength","closeness","betweenness"))
#plot centrality stability
plot(b1c, statistics=c("strength","closeness","betweenness")) 

![1525182282](https://github.com/SachaEpskamp/bootnet/assets/58458637/74a70827-450f-45bd-b559-cc2f748bf55b)

**Comment by SachaEpskamp** [comment]
You misspelled 'statistics' in the `plot(...)` call.

Best,
Sacha

**Comment by dengxuebin** [comment]
> You misspelled 'statistics' in the `plot(...)` call.
> 
> Best, Sacha

It worked，thanks a lot，sorry for my  blunder.

**Comment by SachaEpskamp** [comment]
No problem, happens so many times to me too :)
