### ISSUE TITLE
CS coefficient error

### ISSUE THREAD

**Issue by sarahkertz** [SachaEpskamp/bootnet#11]
I'm getting the following error when trying to estimate the CS-coefficent:

Error in if (!x$type %in% c("node", "person")) { : 
  argument is of length zero

Any suggestions much appreciated!

**Comment by SachaEpskamp** [comment]
Hi, Do you have an example of the code you use?

Best, Sacha

**Comment by sarahkertz** [comment]
I figured it out! Thank you for responding.
