### ISSUE TITLE
I cannot calculate the difference of "closeness".

### ISSUE THREAD

**Issue by dengxuebin** [SachaEpskamp/bootnet#110]
Hi SachaEpskamp
    When I estimated the network, I found I can get the results of differences of "strength" and "edge", but for the "closeness", it didn't work. I guess it is the same for the "betweenness" although I did not try it yet. I want to know why. The code is following, hope your reply. Thanks a lot!
###########
bootnet_nonpar <- bootnet(network, 
                          nBoots = 1000, # number of boot samples
                          nCores = 8)
plot(bootnet_nonpar,"strength", plot ="difference")
plot(bootnet_nonpar,"closeness", plot="difference")  
############

![image](https://github.com/SachaEpskamp/bootnet/assets/58458637/8f8eb155-cf95-42f4-b21a-bdaf5f63f2d7)

**Comment by SachaEpskamp** [comment]
Hi! The default changed quite some time ago and now you need to specifically request closeness and betweenness using the `statistics` arguments in both `bootnet(...)` and `plot(...)`. See https://github.com/SachaEpskamp/bootnet/issues/88.

**Comment by dengxuebin** [comment]
> Hi! The default changed quite some time ago and now you need to specifically request closeness and betweenness using the `statistics` arguments in both `bootnet(...)` and `plot(...)`. See #88.

Thanks for your immediate reply. 👍
