### ISSUE TITLE
How to set alpha parameter of elastic net penalty in estimatenetwork function？

### ISSUE THREAD

**Issue by dengxuebin** [SachaEpskamp/bootnet#112]
Hi，SachaEpskamp,  I have a piece of code like the following, but I don't know how to specify elastic net penalty for estimation. I think the code should employ the Lq penalty as default(i.e., "tuning=0.5" means γ=0.5), right? How to set α parameter from elastic net penalty？ Hope you reply, thanks a lot!

Network<-estimateNetwork(as.matrix(sdrgroup), default = "mgm",
        type = types, criterion ="EBIC",
        level = levelgroup,
        order = 2, threshold = "HW",
        )

**Comment by SachaEpskamp** [comment]
Hi! The `...` in the help page indicate that any argument can be passed to the underlying `mgm` function, so you can just use the `alphaSeq` argument from `mgm` directly in `estimateNetwork`.

**Comment by dengxuebin** [comment]
I got it，thanks  a lot！
