### ISSUE TITLE
failed installing botnet

### ISSUE THREAD

**Issue by rhiens** [SachaEpskamp/bootnet#114]
Dear Sacha
I failed to install botnet and this message always come up :
Registered S3 methods overwritten by 'rgl':
  method               from
  knit_print.rglId         
  knit_print.rglOpen3d     
  sew.rglRecordedplot      
Error in dyn.load(dynlib <- getDynlib(dir)) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rgl/libs/rgl.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rgl/libs/rgl.so, 0x0006): Library not loaded: /opt/X11/lib/libGLU.1.dylib
  Referenced from: <1A5413AB-AD6C-3375-B3B2-B091E2404889> /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/rgl/libs/rgl.so
  Reason: tried: '/opt/X11/lib/libGLU.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/X11/lib/libGLU.1.dylib' (no such file), '/opt/X11/lib/libGLU.1.dylib' (no such file), '/Library/Frameworks/R.framework/Resources/lib/libGLU.1.dylib' (no such file), '/Library/Java/JavaVirtualMachines/jdk-11.0.18+10/Contents/Home/lib/server/libGLU.1.dylib' (no such file), '/var/folders/_r/lsfb4m895_xgvqzmwxlw2xhh0000gn/T/rstudio-fallback-library-path-2143918571/libGLU.1.dylib' (no such file)
Error: package or namespace load failed for ‘bootnet’:
 .onLoad failed in loadNamespace() for 'rgl', details:
  call: rgl.init(initValue, onlyNULL)
  error: OpenGL is not available in this build
In addition: Warning messages:
1: 	Loading rgl's DLL failed. 
	This build of rgl depends on XQuartz, which failed to load.
 See the discussion in https://stackoverflow.com/a/66127391/2554330 
2: Trying without OpenGL... 
> 
I hope you can help me, thank you

**Comment by SachaEpskamp** [comment]
I don't think I can help with this, sorry. This seems to be an issue specific to installing the rgl package for Mac?

**Comment by rhiens** [comment]
Dear Sacha, 
That's right, but I succeeded in installing it; before installing rgl I must install Xquartz. 

thankyou
