### ISSUE TITLE
Cross-lagged panel networks in bootnet

### ISSUE THREAD

**Issue by Tongzhao9417** [SachaEpskamp/bootnet#116]
Hi Sacha, I encountered an error that someone had asked about previously.

I used the bootnet with a custom funtion. Whenever I employed the case-dropping bootstrap, I have to limited only 1 core (nCores = 1) because an error occurs when the cores more than 1: 
`Error in checkForRemoteErrors(val) : 
  one node produced an error: Maximum number of errors in bootstraps reached`

Someone have posted this question but there are no answers. (https://github.com/SachaEpskamp/bootnet/issues/5#issuecomment-507988668) Is the question about "snow" package? This package has been deprecated and the `doSNOW` or `doParallel` maybe better

Thanks for your job!

**Comment by SachaEpskamp** [comment]
Hi, do note that the custom function will need to work from a new and empty R workspace, so you need to load all packages etcetera in the function or the function will not work with nCores > 1.

**Comment by Tongzhao9417** [comment]
> Hi, do note that the custom function will need to work from a new and empty R workspace, so you need to load all packages etcetera in the function or the function will not work with nCores > 1.

Thanks for your reply! It's a little difficult for me to understand "work from a new and empty R workspace". Now, I have move the function code in a new and empty r script, and load all package in this function. Like these:
```
CLPN.fun <- function(df) {
  library(glmnet)
  library(qgraph)
  library(lavaan)
  library(haven)
  library(bootnet)
  #library(parallel)
  library(NetworkToolbox)
  for (i in 1:k){
    set.seed(100)
    lassoreg <- cv.glmnet(as.matrix(df[,1:k]), df[,(k+i)], 
                          family = "gaussian", alpha = 1, standardize=TRUE)
    lambda <- lassoreg$lambda.min 
    adjMat[1:k,i] <- coef(lassoreg, s = lambda, exact = FALSE)[2:(k+1)]
  }
  return(adjMat)
}
```
After that, i run the funtion firstly, and then i load the data and some key parameters. Unfortunately, it not work with nCores >=2 (Good news! It can work with nCores = 2! It didn't work before!)

**Comment by SachaEpskamp** [comment]
I think `k` is not defined in this function.

Best,
Sacha

**Comment by Tongzhao9417** [comment]
> I think `k` is not defined in this function.
> 
> Best, Sacha

Thanks for your patience! Well, how could i pass (or define) the parameter `k` into the funciton?

i can modified the function like this:
```
CLPN.fun <- function(df,k) {
  library(glmnet)
  library(qgraph)
  library(lavaan)
  library(haven)
  library(bootnet)
  #library(parallel)
  library(NetworkToolbox)
  for (i in 1:k){
    set.seed(100)
    lassoreg <- cv.glmnet(as.matrix(df[,1:k]), df[,(k+i)], 
                          family = "gaussian", alpha = 1, standardize=TRUE)
    lambda <- lassoreg$lambda.min 
    adjMat[1:k,i] <- coef(lassoreg, s = lambda, exact = FALSE)[2:(k+1)]
  }
  return(adjMat)
}
```
But the bootnet() couldn't use `fun()` like this: 
```
bootnet(df, fun = CLPN.fun()...)
```
the error info is: ```Error in do.call(.input$estimator, c(list(data), .input$arguments)) : 
  'what' must be a function or character string
In addition: Warning messages:
1: In formals(fun) : argument is not a function
2: In formals(fun) : argument is not a function
```

**Comment by SachaEpskamp** [comment]
Hi Tong,

Please note that you should not use the custom function in `bootnet` but rather in `estimateNetwork`, then use that result in bootnet:

```
network <- estimateNetwork(df, fun = CLPN.fun, k = ...)
boots <- bootnet(network)
```

this should work I think?

**Comment by Tongzhao9417** [comment]
> Hi Tong,
> 
> Please note that you should not use the custom function in `bootnet` but rather in `estimateNetwork`, then use that result in bootnet:
> 
> ```
> network <- estimateNetwork(df, fun = CLPN.fun, k = ...)
> boots <- bootnet(network)
> ```
> 
> this should work I think?

Thank for your reply so quickly. Unfortunately, the bootnet report error again. Here is my full code that follow your recommend. 
1. conduct the function
```
CLPN.fun <- function(df,k) {
  library(glmnet)
  library(qgraph)
  library(bootnet)
  library(NetworkToolbox)
  for (i in 1:k){
    set.seed(100)
    lassoreg <- cv.glmnet(as.matrix(df[,1:k]), df[,(k+i)], 
                          family = "gaussian", alpha = 1, standardize=TRUE,nfolds = 10)
    lambda <- lassoreg$lambda.min 
    adjMat[1:k,i] <- coef(lassoreg, s = lambda, exact = FALSE)[2:(k+1)]
  }
  return(adjMat)
}
```
2. estimate the network
```
Network_CL <- estimateNetwork(df, fun = CLPN.fun, labels = labels, directed = T,
                              k = 16)
```
3. bootnet the result
```
boots <- bootnet(Network_CL,nCores = 2)
```
error info: 
```
Error in checkForRemoteErrors(val) : 
  one node produced an error: Maximum number of errors in bootstraps reached
```
4. Also, this failed again:
```
Boot_CL_2 <- bootnet(Network_CL, nBoots = 5000, nCores = 2, caseN = 25,
                     type = "case",
                     statistics = c("OutExpectedInfluence","InExpectedInfluence"
                                    ), directed = T)
```
If I change the cores more than 2, the error info same as above.

I'm so appreciate for your time and help!

Best,
Tong

**Comment by SachaEpskamp** [comment]
Hi,

See below code which works for me. I adapted your code slightly: I assumed the data would contain only columns for t1 and t2 variables so determine `k` from data, I remove the `set.seed` call as this messes up the bootstrapping, and I defined the `adjMat` object which you did not define before. This works ok.

I do have to note that I have strong objections to using this code and to estimating the cross-lagged panel network model as defined here. My main objections are:

1. The use of cross-validation leads to poor specificity as well as ambiguity due to the random seed used.

2. The model does not adequatly separate within- and between-person sources of variation (see also the discssion on the CLPM and random intercept CLPM).

See also https://link.springer.com/article/10.1007/s11336-020-09697-3 for my thoughts on modeling panel data.

```
ibrary("bootnet")

# CLPN function:
CLPN.fun <- function(df) {
    library(glmnet)
    library(qgraph)
    library(bootnet)
    library(NetworkToolbox)

    k <- ncol(df) / 2
    adjMat <- matrix(0, k, k)
    for (i in 1:k){
        # set.seed(100) # <- this will lead to issues with bootstrapping
        lassoreg <- cv.glmnet(as.matrix(df[,1:k]), df[,(k+i)],
                              family = "gaussian", alpha = 1, standardize=TRUE,nfolds = 10)
        lambda <- lassoreg$lambda.min
        adjMat[1:k,i] <- coef(lassoreg, s = lambda, exact = FALSE)[2:(k+1)]
    }
    return(adjMat)
}

# Generate some data:
t1 <- matrix(rnorm(1000*3),1000,3)
beta <- diag(0.5, 3)
beta[2,1] <- beta[3,2] <- beta[1,3] <- 0.25
t2 <- t1 %*% t(beta) +  matrix(rnorm(1000*3),1000,3)
df <- as.data.frame(cbind(t1,t2))
names(df) <- c(paste0("T1_V",1:3), paste0("T2_V",1:3))

# Fit CLPN model in bootnet:
library("bootnet")
Network_CL <- estimateNetwork(df, fun = CLPN.fun, labels = paste0("V",1:3), directed = TRUE)

# Compare to true network:
layout(t(1:2))
plot(Network_CL, layout = "circle", theme = "colorblind", title = "Estimated CLPN", diag = TRUE)
qgraph::qgraph(t(beta), layout = "circle", theme = "colorblind", title = "True CLPN", diag = TRUE)

# Bootstrap results:
boots <- bootnet(Network_CL, nCores = 8)

# Plot bootstrapped CIs:
plot(boots)
```

**Comment by Tongzhao9417** [comment]
Thank for your reply! It's help me a lot :)

Actually, I strongly agree with your comments that should not estimate cross-lagged network. However, the editor requested that I present these results in the Results section, so I had to do it this way. By the way, your suggestions are very important, and we are prepared to include our estimate results and your options in the supplementary materials.

Please accept my sincere appreciate, that helps me a lot. 
Best wish,
Tong
