### ISSUE TITLE
Mixing different data types in GGM - preprocessing ?

### ISSUE THREAD

**Issue by WivineB** [SachaEpskamp/bootnet#118]
Hello ! This is not an issue per se, but more a question for which I couldn't find an answer, so please feel free to close this.

I have a dataset with a lot of variability in the measures that I'll treat as continuous, such as likert scales but also variables derived from a neuropsychological assessment (some are in milliseconds,  others in percentages or number of correct trials etc). Importantly, none are dichotomous. I wondering if there are any considerations on estimating networks such different types of measures, and if I should consider things like paranormal transformation or simply center and scaling such data ?

Thank you for your insights on this !

Best, 

Wivine.

**Comment by SachaEpskamp** [comment]
Hi Wivine,

Centering and scaling is typically not needed for models in bootnet as the models show only standardized effects. As for what transformations may be appropriate that is very hard to say and really depends on the data. The Spearman correlations / rank transformation generally work well if data are not normal, but for fine grained continuous variables perhaps the NPN is more appropriate. For count variables it would be better to use `mgm` (which is supported in bootnet) together with the Poisson type for those variables.

Best,
Sacha
