### ISSUE TITLE
How to display computing progress when using estimateNetwork function with mgm method?

### ISSUE THREAD

**Issue by dengxuebin** [SachaEpskamp/bootnet#119]
Hi SachaEpskamp
     I found an error when run the following code, hope your reply ,thanks a lot!

Network<-estimateNetwork(as.matrix(sdrgroup), default = "mgm",
        type = types,
        level = levelgroup,
        order = 2, threshold = "HW", pbar=T
        )

Error in mgm::mgm(data, verbatim = !verbose, warnings = verbose, signInfo = FALSE,  : 
  formal argument "pbar" matched by multiple actual arguments

**Comment by SachaEpskamp** [comment]
Currently all direct output from an underlying estimation method is supressed, so this is not possible at the moment. 

Best,
Sacha

**Comment by dengxuebin** [comment]
> Currently all direct output from an underlying estimation method is supressed, so this is not possible at the moment.
> 
> Best, Sacha

I got it. Thanks
