### ISSUE TITLE
correlation matrix is not positive definite

### ISSUE THREAD

**Issue by ttsunmeng** [SachaEpskamp/bootnet#120]
Hi there,
Thank you so much for inventing such a great tool. I am trying to push the limit of calculating the partial network with only 14 samples. I could play with the number of variables by inputting more or less. The code only works when I have fewer variables than #samples. Is there a way to go around it? Thank you.

**Comment by SachaEpskamp** [comment]
Hi!

No generally most estimation methods only work when N (sample size) > P (nodes(. Some estimation methods work with N < P, but this is more in terms of hundreds / thousands. N=14 is definitly too low.

Best,
Sacha
