### ISSUE TITLE
Can not plotting subset bootstrapped estimates when using "plot='difference' "

### ISSUE THREAD

**Issue by dengxuebin** [SachaEpskamp/bootnet#121]
Hi SachaEpskamp
     I used the following code for subsetting edges, but found "subset" cannot work. All the edges were calculated. I wonder whether "subset" is  supported for "plot='difference' ". Expect your reply. Thanks a lot!

keywords <- paste(ew_visible$V1, ew_visible$V2, sep = "--") # "keywords" is a vector including edges of interest.
subset <- boot_npr$bootTable$id[grep(paste(keywords, collapse="|"), boot_npr$bootTable$id)]
plot(boot_npr, "edge", plot = "difference",onlyNonZero = TRUE, subset=subset, order = "sample")

**Comment by SachaEpskamp** [comment]
This is indeed not supported for the difference plot!
