### ISSUE TITLE
Node-Dropping Bootstrap: "Lowest Lambda was selected"

### ISSUE THREAD

**Issue by Hans-Anton** [SachaEpskamp/bootnet#122]
Hi,
for my network analysis, I am also using the node-dropping bootstrap. 
```
BootCentralityNodeDropping <- bootnet(NetworkData, default = "EBICglasso",   
                 nBoots=NumberOfBootStraps, 
                 type = "node",
                 labels = colnames(NetworkData))
```
This always leads to the warning: 
_"An empty network was selected to be the best fitting network. Possibly set 'lambda.min.ratio' higher to search more sparse networks. You can also change the 'gamma' parameter to improve sensitivity (at the cost of specificity).
Note: Network with lowest lambda selected as best network: assumption of sparsity might be violated."_
At first, I thought this problem was because of the network structure within my data, but it also occurred, when I tried it with the PTSD-Data of the Armour Paper used for the "A Tutorial on Regularized Partial Correlation Networks" (2017) paper.

This error does not occur, when estimating the network structure itself or for the nonparametric and the case-dropping bootstrap. Now I am wondering whether I should include the node-dropping and if I do how to interpret the results.
Thank you for your help!

**Comment by SachaEpskamp** [comment]
Hi! This is quite a common message and not always something to worry about. However, it happens often if your sample size is very high, and in this case you might want to consider an unregularized estimator such as` default = "ggmModSelect" `or `default = "pcor", threshold = "sig"`.
