### ISSUE TITLE
partial correlations

### ISSUE THREAD

**Issue by 000Annemarie** [SachaEpskamp/bootnet#123]
A quick question to check:

Even when selecting corMethod = 'cor', the following script still results in a partial correlations network, right?
         estimateNetwork (data, default = "EBICglasso", corMethod = "cor")

Thank you in advance; I just want to be sure.

**Comment by SachaEpskamp** [comment]
In this case regularized partial correlations, correct. The `corMethod` argument controls how the *input* correlation algorithm is computed that is subsequently used (in this case using `glasso`) to compute the (regularized) partial correlations.

**Comment by 000Annemarie** [comment]
Perfect, thank you for your quick response.
