### ISSUE TITLE
Code credit

### ISSUE THREAD

**Issue by falkcarl** [SachaEpskamp/bootnet#128]
Hi Sacha,

I recently added a package to GitHub (e.g., (https://github.com/falkcarl/EMgaussian/blob/main/R/ggm.R) that borrows and modifies a couple of lines of code from qgraph (see lines 347 to 350) and a couple lines from bootnet (e.g., lines 211 to 213, which are similar code mentioned here: SachaEpskamp/bootnet#65).

These are marked locally in comments and mentioned in the copyright notice at the top of the relevant file. qgraph and bootnet are both released under GPL-2; this package is released under GPL-3.

My question is whether you would additionally like the code acknowledged in the package DESCRIPTION file (e.g., you/Eiko with ctb status), or if the notice mentioned here is enough.

Thank you!
Carl

**Comment by SachaEpskamp** [comment]
Hi Carl,

Sure the notice now is enough! No need to also mention me in DESCRIPTION. Thanks!

Best,
Sacha
