### ISSUE TITLE
trouble with estimateNetwork function in R

### ISSUE THREAD

**Issue by tryingmybest25** [SachaEpskamp/bootnet#130]
Hi, 
I am trying to conduct a Network Analysis in R, but the bootnet package is not loading/installing on my device so I can't use the estimateNetwork function. Is it possible to estimate a network in a different way? or is there something I can do to get bootnet to cooperate? 
Thanks (in advance) for the insights!

**Comment by SachaEpskamp** [comment]
Hi! If you cannot install an R package that seems to be more of an issue with R than bootnet. I cannot really help with that. Perhaps you can ask on stackoverflow.com?
