### ISSUE TITLE
trouble with bootnet function in R

### ISSUE THREAD

**Issue by Psych-MaXu** [SachaEpskamp/bootnet#135]
Hi Sacha,
I encountered an issue when using the bootnet function to calculate the stability of the "bridgeInDegree" and "bridgeOutDegree" centrality.
Firstly, i used bridge function (Networktools package) to calculate the "bridgeInDegree" and "bridgeOutDegree" . This fuction is normal, so i continue to use bootnet function to calculate the stability of the "bridgeInDegree" and "bridgeOutDegree" . But it can not output the stability of the "bridgeInDegree" and "bridgeOutDegree" centrality.
here is my code
```
Boot_CL_2 <- bootnet(Network_CL,  nBoots = 1000 , 
                     type = "case", 
                     statistics = c("edge", "bridgeInDegree",
                                    "bridgeOutDegree"), 
                     directed = `TRUE,`
                     communities = groups)
corStability(Boot_CL_2)
=== Correlation Stability Analysis === 
Sampling levels tested:
   nPerson Drop%  n
1     3448  75.0  5
2     4521  67.2 11
3     5594  59.4  6
4     6667  51.7 10
5     7740  43.9 12
6     8813  36.1 13
7     9886  28.3  9
8    10959  20.6 10
9    12031  12.8 13
10   13104   5.0 11
Maximum drop proportions to retain correlation of 0.7 in at least 95% of the samples:
edge: 0.75 (CS-coefficient is highest level tested)
  - For more accuracy, run bootnet(..., caseMin = 0.672, caseMax = 1) 
Accuracy can also be increased by increasing both 'nBoots' and 'caseN'.
```
Looking forward to your thoughts and suggestions! Thank you a lot!

**Comment by Psych-MaXu** [comment]
The bridge function can successfully output the "bridgeInDegree" and "bridgeOutDegree," but the bootnet function fails to provide the stability of these metrics. Therefore, I suspect there might be some errors in the bootnet function.

**Comment by SachaEpskamp** [comment]
Hi! The backticks should be removed on the `directed` argument. Is the use of `directed` intended? What default set did you use to estimate `Network_CL`? Perhaps the network is not directed making `bridgeInDegree` and `bridgeOutnDegree` not working?

**Comment by SachaEpskamp** [comment]
I will close this issue for now but please let me know if you experience more problems.
