### ISSUE TITLE
Add support for `parabar` parallel backend

### ISSUE THREAD

**Issue by mihaiconstantin** [SachaEpskamp/bootnet#137]
Hi Sacha,

I am trying to add support for the `parabar` backend, but I need to check with you first where parallelization is currently needed in `bootnet`. Can I safely assume that, at commit [9df9eab](https://github.com/SachaEpskamp/bootnet/commit/9df9eabf009da80f1ea69b969365a77b33a9f5ad), the following place are _the only_ places where a parallel backend is required?

In `R/bootnet.R`:

https://github.com/SachaEpskamp/bootnet/blob/9df9eabf009da80f1ea69b969365a77b33a9f5ad/R/bootnet.R#L612-L613

https://github.com/SachaEpskamp/bootnet/blob/9df9eabf009da80f1ea69b969365a77b33a9f5ad/R/bootnet.R#L788-L790

In `R/parSim.R`:

https://github.com/SachaEpskamp/bootnet/blob/9df9eabf009da80f1ea69b969365a77b33a9f5ad/R/parSim.R#L64-L65

https://github.com/SachaEpskamp/bootnet/blob/9df9eabf009da80f1ea69b969365a77b33a9f5ad/R/parSim.R#L95-L96

Best,
Mihai

**Comment by SachaEpskamp** [comment]
Hi Mihai,

The `parSim` function has actually been ported to the [parSim](https://github.com/SachaEpskamp/parSIM) package, which I use a lot for simulation studies. I should also make that imported in bootnet instead of having this old code in bootnet. Other than that, indeed only the bootnet function I think.

Best,
Sacha

**Comment by mihaiconstantin** [comment]
Ah, I see. In that case:

1. The PR with support for `parabar` backends need to in the context of the `parSim` package.
2. The `bootnet::bootnet` function needs to be updated to use `parSim::parSim`.

I'll work on (1) and also give (2) a try. Since there are no tests for `bootnet`, it would be handy if you could take a closer look at the changes for (2). After these are done, I think we can also finally close #82.

Thanks for the clarifications!
