### ISSUE TITLE
Error with plotting bootnet results object

### ISSUE THREAD

**Issue by lindoyle** [SachaEpskamp/bootnet#15]
I am trying to plot 
```
plot(boot1, "strength", plot="difference", order="sample", labels=F) 
```
But get the following error
```
Expected significance level given number of bootstrap samples is approximately: 0.05
Error in FUN(X[[i]], ...) : object '.group' not found
```
I have also tried
```
plot(boot1, "strength", plot="difference", order="sample", labels=F, inherit.aes = FALSE) 
```
But it doesn't help. 
This code was working and then I pulled bootnet from github just before this error occured so could it be related to some updates? Any help would be greatly appeciated.

**Comment by SachaEpskamp** [comment]
This seems to be working with the current version. Do you still get the error?

Best, Sacha

**Comment by lindoyle** [comment]
Yes, it's resolved.
