### ISSUE TITLE
Centrality Tables

### ISSUE THREAD

**Issue by pevitrb** [SachaEpskamp/bootnet#19]
Novice network analyzer here, 

I've successfully obtained my network plot and with centrality plots, but am having an issue in generating a table with my numerical centrality indices. I'd like one to report precise numbers for a manuscript.

I've tried several codes yet nothing seems to work. I'm conducting networks in R using bootnet.
I have experimented with different syntax as per my internet search and reading of different articles, along with using the '?centrality' command in R.

One error I've repeatedly gotten is "edgeweights must have 2 or 3 columns" - any insight into this issue would be helpful as well.

Let me know if you need more info for assistance. 

Thanks in advance.

**Comment by SachaEpskamp** [comment]
Hi, 

The network is stored in the element $graph of the estimateNetwork output. So you can use that:

```
Network <- estimateNetwork(...)
library("qgraph")
estimateNetwork(Network$graph)
```

Best, Sacha
