### ISSUE TITLE
Error computing centrality statistics in node-dropping bootstrap

### ISSUE THREAD

**Issue by cmg212** [SachaEpskamp/bootnet#2]
Hi again Sacha, 

In fact, I am experiencing another bug when the node-dropping bootstrap is calculating centrality statistics: 

`Error in data.frame(name = name, type = "strength", node1 = x[["labels"]],  : arguments imply differing number of rows: 1, 5, 2`

A reproducible example: 

`library("psych")`
`data(bfi)`
`bfiSub <- bfi[,11:15]`

`NodeDrop <- bootnet( bfiSub , nBoots = 20 , type = "node" , default="EBICglasso",   
                                     computeCentrality=TRUE)`

Running non-parametric and person-dropping bootstrapping, or node-dropping with `centralityCompre = FALSE`, does not return the error.

I am using R 3.3.1. for Mac OS X.  

Thanks for all your help!
Conor

**Comment by SachaEpskamp** [comment]
Thanks for reporting and the reproducible example! I've fixed this bug.

Maybe of interest, bootnet now supports parallel computing. e.g.,

```
NodeDrop <- bootnet( bfiSub , nBoots = 1000, type = "node" , default="EBICglasso", 
                     computeCentrality=TRUE, nCores = 8)
```

Uses 8 cores rather than 1, making the computation much faster.
