### ISSUE TITLE
IsingGenerator() errors 

### ISSUE THREAD

**Issue by mjbsp** [SachaEpskamp/bootnet#21]
I am working with netSimulator() using the most recent version of bootnet from Github. When trying to simulate network estimation using IsingFit I receive the following error message.

"Error in dataGenerator(nCases, inputResults) : \n  Input must be a list containing elements 'graph' and 'intercepts'\n"

A reproducible example:

```

devtools::install_github("sachaepskamp/bootnet")
library(bootnet)

doesnotwork <- netSimulator(nCases = 1000, nReps = 5, default = c("IsingFit"), dataGenerator = IsingGenerator())

```

**Comment by SachaEpskamp** [comment]
That's because you are missing an input. E.g., the graph you want to simulate under, or a function generating such graphs. In this case, input must be a list containing element graph (weights matrix) and intercepts (thresholds).

**Comment by mjbsp** [comment]
Thanks. I didn't catch this.
