### ISSUE TITLE
Error in case-dropping Bootstrap

### ISSUE THREAD

**Issue by BennTR** [SachaEpskamp/bootnet#27]
Running into an error in RStudio that I have not previously. Any assistance would be very much appreciated. 

Graph_lassoRandom2<-estimateNetwork (Data3, default="EBICglasso")
 boot1random2<- bootnet(Graph_lassoRandom2, type="case", nBoots=2500, nCores=8)
Note: bootnet will store only the following statistics:  edge, strength, outStrength, inStrength
Estimating sample network...
Estimating Network. Using package::function:
  - qgraph::EBICglasso for EBIC model selection
    - using glasso::glasso
  - qgraph::cor_auto for correlation computation
    - using lavaan::lavCor
Variables detected as ordinal: R_B1; R_B2; R_B3; R_B4; R_B5; R_C1; R_C2; R_C3; R_C4; R_C5; R_C6; R_C7; R_D1; R_D2; R_D3; R_D4; R_D5
Bootstrapping...
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 08m 54s
Computing statistics...
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 01m 01s
Warning message:
In EBICglassoCore(S = S, n = n, gamma = gamma, penalize.diagonal = penalize.diagonal,  :
  A dense regularized network was selected (lambda < 0.1 * lambda.max). Recent work indicates a possible drop in specificity. Interpret the presence of the smallest edges with care. Setting threshold = TRUE will enforce high specificity, at the cost of sensitivity.
> corStability(boot1random2)
=== Correlation Stability Analysis === 

Sampling levels tested:
   nPerson Drop%   n
1       94  74.9 257
2      123  67.2 230
3      152  59.5 253
4      181  51.7 263
5      210  44.0 232
6      240  36.0 243
7      269  28.3 236
8      298  20.5 276
9      327  12.8 266
10     356   5.1 244

Maximum drop proportions to retain correlation of 0.7 in at least 95% of the samples:

edge: Could not be computed (likely due to non-finite values) 

strength: Could not be computed (likely due to non-finite values) 

Accuracy can also be increased by increasing both 'nBoots' and 'caseN'.

Quick Side question: How does one remove the bootstrap mean from the bootstrap confidence interval graph? I tend to see this published without the mean show. Thank you for your time.

**Comment by SachaEpskamp** [comment]
This should be fixed now. The mean has been added recently, hence it has not been used yet much in publications.
