### ISSUE TITLE
Empty network in bootnet, but not qgraph

### ISSUE THREAD

**Issue by Algebreaker** [SachaEpskamp/bootnet#29]
I'm still getting my head round network analysis, but I'm having an issue I can't quite figure out where a network that looks pretty normal when I estimate it with qgraph 
`graph <-qgraph(data, graph = "glasso", layout = "spring", sampleSize = nrow(data), groups = groups, vTrans = 150, legend = TRUE, borders = FALSE)`
will not run in bootnet ('Empty network was selected to be the best fitting network.'):
`Network <- estimateNetwork(data, default = "EBICglasso")
case <- bootnet(Network, default ="EBICglasso", nBoots = 2500,type = "case", statistics = c("strength", "closeness", "betweenness"))`
unless I set the tuning parameter to 0. Of course I would like to estimate the network I obtained with the qgraph estimation method and not one where I've fiddled with the tuning parameter? Why would I get an empty network if I can clearly see a non-empty network with the qgraph approach?

**Comment by SachaEpskamp** [comment]
Hi,

The input to qgraph should be a correlation matrix, but the input to bootnet should be the raw data. Perhaps this is going wrong?

Best, Sacha

**Comment by Algebreaker** [comment]
Thanks for the amazingly quick reply!
No, I actually tried the raw data input first (as per the manual) and only resorted to the above attempt when I started getting the 'empty network' error and saw that some people seem to have used the 'estimateNetwork' output.

**Comment by Algebreaker** [comment]
Any news on what might be causing this?

**Comment by SachaEpskamp** [comment]
There isn't enough information for me to see this clearly. The call to qgraph in bootnet is pretty straightforward:

https://github.com/SachaEpskamp/bootnet/blob/master/R/defaultFunctions.R#L87-L206

So probably the discrepancy lies in the input correlation matrix you use in qgraph. How do you compute the input correlation matrix?

**Comment by Algebreaker** [comment]
Yes, I thought that might be it as well. Initially I just used `data <- cor(rawdata, use = "pairwise.complete.obs")` but I've now also tried `data <- cor_auto(rawdata)` to see if it makes a difference (it's binary data though, so it shouldn't?).
When using the cor_auto function, I'm getting the mysterious   `Correlation matrix is not positive definite. Finding nearest positive definite matrix` message which I also get when running the bootnet case-dropping boostrap (which again only runs if I change the tuning parameter to something below 0.3). Sorry, I'm probably just being very dense somewhere...

**Comment by SachaEpskamp** [comment]
`cor_auto` will compute tetrachoric correlations if your data is binary, so that is very different from `cor(...)`. That warning generally is very bad news too. But with binary data, I would compute an Ising model instead of a GGM (default = `IsingFit`).

**Comment by Algebreaker** [comment]
Using the Ising model solved the issue - many, many thanks!

PS: Just incidentally (I don't want this to get too OT): I now can't seem to use more than one graph estimated with `IsingFit` in a list to plot the centrality measuresin the same figure (`(list) object cannot be coerced to type 'double'`)?

**Comment by SachaEpskamp** [comment]
That bug has now been solved in the qgraph devel version!
