### ISSUE TITLE
Error computing betweenness from node-dropping bootstraps 

### ISSUE THREAD

**Issue by cmg212** [SachaEpskamp/bootnet#3]
Hi again Sacha!

I have noticed another error when computing centrality statistics from the node-dropping bootstrap, particularly when calculating betweenness centrality of certain bootstraps. I have noticed it in networks of a 'smaller' sample size (e.g. < 50 people). An example of the error is: 

`Error in lab(Betweenness, Labels) : 
  'names' attribute [5] must be the same length as the vector [4]`

It's doesn't always occur, but it should be reproducible in the following (admittedly, slightly tedious) code:

`library("psych")`
`data(bfi)`
`repBoots <- function( times ) {` 
       `boot <- vector(mode="list", length=times)`
      `for(i in 1:times ) {`       
 `boot[[i]] <- bootnet(na.omit(bfi[sample(1:nrow(bfi),runif(1,10,50)),11:15]) ,` 
                                          `nBoots = 25 , type = "node" , default = "EBICglasso")`
 ` }`
  `boot`
`}`

`repBoots(times=20)`

It seems that the betweenness calculations of certain bootstrap networks are returning vector lengths smaller than the number of nodes in those networks?

Thanks again,
Conor

**Comment by SachaEpskamp** [comment]
Hi Conor,

Thanks again!

This is a known bug with the CRAN version of qgraph. Try updating it to the Github version. I'll likely update the CRAN version next week.

Best, Sacha

**Comment by cmg212** [comment]
Ah, works perfectly now. 

Thanks for the super quick replies!
Conor
