### ISSUE TITLE
Error in bootnet after update

### ISSUE THREAD

**Issue by IrinaVanzhula** [SachaEpskamp/bootnet#30]
Hi Sasha,

I am getting an error calculating strength centrality stability after installing the update. I was able to run this exact code with no issues before and CS was calculated then. I am using Spearman correlation for this network. I am getting the error "_strength: Could not be computed (likely due to non-finite values)"_

I am pasting my code below. Thank you for your help! 

MMIEnetwork1 <- estimateNetwork(MMIE, default="EBICglasso", corMethod = "cor", corArgs=list(method = "spearman", use = "pairwise.complete.obs"))
MMIE1boot1<- bootnet(MMIEnetwork1, nBoots=1000,nCores=4)
MMIE1boot2 <- bootnet(MMIEnetwork1, nBoots=1000,nCores=4, type="case")
corStability(MMIE1boot2)

**Comment by SachaEpskamp** [comment]
I think this is solved now! Could you check?

**Comment by IrinaVanzhula** [comment]
Yes, it is! Thank you.


Thank you,

Irina Vanzhula, M.S.
Doctoral Candidate in Clinical Psychology
Eating Anxiety Treatment (EAT) Lab
www.louisvilleeatlab.com<http://www.louisvilleeatlab.com>
Department of Psychological and Brain Sciences
University of Louisville
Phone: 502-852-4340
________________________________
