### ISSUE TITLE
bootstrapping, empty networks, and corStability

### ISSUE THREAD

**Issue by mayakup** [SachaEpskamp/bootnet#31]
Hello. I have a question regarding the corStability function:
when I bootstrap case-dropping type (total of 487 cases), some permutations of the network return empty, and running corStability results in an error message. I looked at the code, and I was wondering if it is possible for me to bypass it by having the cor0 function return 0 instead of NA?

**Comment by SachaEpskamp** [comment]
Hi Mayakup, I think this is solved now in the new version. Could you check?

**Comment by mayakup** [comment]
Indeed solved - thank you very much.
