### ISSUE TITLE
Error nonparametric bootstrapping- dense network

### ISSUE THREAD

**Issue by dpmoriarity** [SachaEpskamp/bootnet#34]
Hi Sacha,

Getting an error with the strength metric (error below) when doing the nonparametric and case-dropping boostraps on a dense network. I only get the below error when bootstrapping (but I am warned that it is a dense network when estimating the original network). Thanks for your help with this!

Network with lowest lambda selected as best network: assumption of sparsity might be violated.
Computing statistics...
Error in data.frame(name = name, type = "strength", node1 = x[["labels"]], :
arguments imply differing number of rows: 1, 18, 13

**Comment by SachaEpskamp** [comment]
Is this still the case in the latest version? I updated bootnet recently to resolve some errors here.

**Comment by dpmoriarity** [comment]
Yup, this is still coming up. During the boostrapping the note "Network with lowest lambda selected as best network: assumption of sparsity might be violated." comes up frequently for both.

Code:
c1  <- bootnet(NoImpair_Nw, nBoots = 1000,statistics=c("edge","strength","expectedInfluence"), labels = labels_S, type = "nonparametric")
c2 <- bootnet(NoImpair_Nw, nBoots = 1000, statistics=c("edge","strength","expectedInfluence"), labels = labels_S, type = "case")


Error for nonparametric:

Computing statistics...
Error in data.frame(name = name, type = "strength", node1 = x[["labels"]],  : 
  arguments imply differing number of rows: 1, 18, 13
In addition: Warning message:
In EBICglassoCore(S = S, n = n, gamma = gamma, penalize.diagonal = penalize.diagonal,  :
  A dense regularized network was selected (lambda < 0.1 * lambda.max). Recent work indicates a possible drop in specificity. Interpret the presence of the smallest edges with care. Setting threshold = TRUE will enforce higher specificity, at the cost of sensitivity.


Error for case-dropping:

Computing statistics...
Error in data.frame(name = name, type = "strength", node1 = x[["labels"]],  : 
  arguments imply differing number of rows: 1, 18, 13

**Comment by SachaEpskamp** [comment]
Thanks! Could you provide a reproducible example of this bug? 

The warning is related to the EBICglasso performance issues, discussed on some blogs last year:

- http://psychosystems.org/glasso_developments
- http://psychosystems.org/qgraph_1.5
- http://psychosystems.org/bootnet_1.1

**Comment by dpmoriarity** [comment]
Hi Sacha,

Sorry for the delay, was traveling for a bit.

The reproducible example won't be necessary, because, to my embarrassment, this one was due to a typo in the label function. The labels I specified had more variables than were included in this particular network. Once I fixed this the error didn't come up anymore. Sorry about that!
