### ISSUE TITLE
installation trouble on macs and with mybinder

### ISSUE THREAD

**Issue by rschmaelzle** [SachaEpskamp/bootnet#35]
Hello, 
i've been able -after some trouble- to get bootnet run on my mac. As it often goes with troubleshooting, isolating the root cause is no longer possible - it all hangs together in a complex network... Anyway, what seems to be problematic on my mac and with R was sth. along the g++ compiler. 

Now being able to work with bootnet on my Mac, I wanted to share the joy with others and get it to run in the cloud via mybinder.org. However, when firing up virtual machines via binder, i again am running into installation issues that are now even harder to diagnose since everything runs remotely. I haven't been able to find an exact dependency list for bootnet, but one particular think I ran into trouble with was the "car" library. To complicate the matter, the binder only installs R3.4.4, but car is apparently not working with this. However, i thought that bootnet existed already with R3.4.4? Any suggestions are welcome.
Thank you, Ralf.

**Comment by SachaEpskamp** [comment]
Hi Ralf,

Unfortunately compiling from source code is quite a hassle, especially given the massive amount of R packages and poor backward compatibility in R. I wrote some things about this actually in a recent paper:

https://journals.sagepub.com/doi/full/10.1177/2515245919847421

Here I think using an outdated R version is a big problem, and I would not know how to install the latest bootnet version. You could try to use checkPoint / MRAN to install an older version, but that is also not really ideal..

I'll close this issue for now.

**Comment by rschmaelzle** [comment]
thank you - that makes sense - and the docker image provided in the article
helped me overcome the issue at least partly. best ralf
