### ISSUE TITLE
after plot(), browser() appears when type is specified in bootnet

### ISSUE THREAD

**Issue by JolandaKossakowski** [SachaEpskamp/bootnet#36]
when the type argument is specified to be "person" or "case" in a bootnet object, I get the browser() in R when I want to plot the results.

## this works:

library(bootnet)
library("psychTools")
data(bfi)
bfiSub <- bfi[,1:25]

# Estimate network:
Network <- estimateNetwork(bfiSub, default = "EBICglasso")

Results1 <- bootnet(Network, nBoots = 1000, nCores = 8
<img width="1280" alt="Screenshot 2019-10-08 at 09 58 00" src="https://user-images.githubusercontent.com/9463613/66377569-24a8bf00-e9b2-11e9-968b-40b167344594.png">
)

# Plot bootstrapped edge CIs:
plot(Results1, labels = FALSE, order = "sample")

## This doesn't work

library(bootnet)
library("psychTools")
data(bfi)
bfiSub <- bfi[,1:25]

# Estimate network:
Network <- estimateNetwork(bfiSub, default = "EBICglasso")

Results1 <- bootnet(Network, nBoots = 1000, nCores = 8, type = "person")

# Plot bootstrapped edge CIs:
plot(Results1, labels = FALSE, order = "sample")

**Comment by SachaEpskamp** [comment]
Oh oh, it seems that I was caught red-handed with my hand in the debugging jar... Fixed now!
