### ISSUE TITLE
bootnet

### ISSUE THREAD

**Issue by hyerin1118** [SachaEpskamp/bootnet#37]
Hi, I am fairly new to coding in R. I am trying to load the library(“bootnet”), but it says that there is no bootnet. I installed the package and I see bootnet when I search for it in my downloaded packages.

**Comment by SachaEpskamp** [comment]
Hi, did you try to install the package with:

`install.packages("bootnet", dep = TRUE)`

And what does this give as message?

**Comment by hyerin1118** [comment]
Thank you for your reply!

Sure, it says the following:

Installing package into ‘/Users/HyeRin/Library/R/3.5/library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.5/bootnet_1.2.4.tgz'
Content type 'application/x-gzip' length 301621 bytes (294 KB)
==================================================
downloaded 294 KB

Then when I load library("bootnet"), it says:
> library(bootnet)
Error: package or namespace load failed for ‘bootnet’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘cmprsk’
>

Oh, I see! I had to download cmprsk! I got it!

Thank you!
