### ISSUE TITLE
Issue with EstimateNetwork

### ISSUE THREAD

**Issue by shrutisram** [SachaEpskamp/bootnet#38]
When running networks, I updated R, R Studio and all packages but am now getting the error:
Error in estimateNetwork(data, default = c("none", "EBICglasso", "pcor",  : 
  could not find function "estimateNetwork"

When I try to load bootnet, I get the error:
Error: package or namespace load failed for ‘bootnet’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘Epi’

When I try to load Epi, it works but does not show up under my packages, so now the EstimateNetwork function does not work.

**Comment by SachaEpskamp** [comment]
Install the Epi package and try to load bootnet again. You will probably get a different message for a different package to install. So repeat the process for that...

**Comment by shrutisram** [comment]
The issue seems to be that the Epi package is not loading. I get feedback saying it has loaded but it does not show up, and when I run bootnet again I get the same package (to load Epi)

**Comment by SachaEpskamp** [comment]
Can you install and load the Epi package? I don't think this problem is due to bootnet itself..
