### ISSUE TITLE
estimatebootnet

### ISSUE THREAD

**Issue by ciaranodriscoll** [SachaEpskamp/bootnet#4]
HI,

Recently started having an issue on different machines. Script used to run fine now getting error: "Error in estimateNetwork(network, default = "EBICglasso", tuning = 0.5,  :   could not find function "estimateNetwork"

EBICgraph <- estimateNetwork(network, default = "EBICglasso", tuning = 0.5, corMethod = ("cor_auto"), missing = ("pairwise"))

**Comment by SachaEpskamp** [comment]
Did you load the bootnet package before? e.g.,

`
library(bootnet)
`

**Comment by ciaranodriscoll** [comment]
Yes,
ggplot2 and tibble had to be loaded separately as failed to load under the bootnet

**Comment by ciaranodriscoll** [comment]
When I load the packages that fail to load under bootnet and then run library(bootnet) again, it works. Not sure why this occurs though.

**Comment by SachaEpskamp** [comment]
What do you mean with "failed to load under bootnet"?

**Comment by ciaranodriscoll** [comment]
This is an example, the package that fails to load can differ. 

> library(bootnet)
Loading required package: ggplot2
Want to understand how all the pieces fit together? Buy the ggplot2
book: http://ggplot2.org/book/
Error: package or namespace load failed for ‘bootnet’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘zoo’

**Comment by SachaEpskamp** [comment]
Did you try installing the 'zoo' package as suggested by the warning message?

**Comment by ciaranodriscoll** [comment]
That's what I do. I call library(bootnet), then load the packages that fail, then I call library(bootnet) again and it works. That's the workaround. Just highlighting an issue as it wasn't a requisite before. Sounds like it a novel error, although it does occur across my machines.
