### ISSUE TITLE
"Correlation matrix is not positive definite"

### ISSUE THREAD

**Issue by patkgoh** [SachaEpskamp/bootnet#40]
Hi Sacha,
I believe my issue is similar to one already posted, but I'm posting a separate entry just in case.

I'm getting an error when attempting to run the estimateNetwork function. 
Error in bootnet_correlate(data = data, corMethod = corMethod, corArgs = corArgs,  : 
  Correlation matrix is not positive definite.

The code I'm using is as follows:
T_W58 <- read.csv("Teacher_Wave 58.csv")
T58_Network <- estimateNetwork(T_W58, default = "EBICglasso")

My understanding was that in the past, the function has found the nearest positive definite matrix, so I wanted to check with you. Thanks for the help!

**Comment by SachaEpskamp** [comment]
Hi Patrick,

Yes that default was changed because finding the nearest positive definite matrix led to unstable results. I would use Spearman correlations in this case (`corMethod = "cor", corArgs = list(method = "spearman")`).

Best, Sacha

**Comment by T2Flair** [comment]
> 

Hi,
I have encountered the same error.
However, when I use :  `Network <- estimateNetwork(DATA, corMethod = "cor", corArgs = list(method = "spearman"))`

It has a error
`Error in do.call(.input$estimator, c(list(data), .input$arguments)) : 
  'what' must be a function or character string
In addition: Warning messages:
1: In formals(fun) : argument is not a function
2: In formals(fun) : argument is not a function`

**Comment by SachaEpskamp** [comment]
You either have to use the `fun` argument or the `default` argument to tell `estimateNetwork` what estimation function should be used.

**Comment by chengjuanChen** [comment]
Hi Sacha, I got the same error and although I have tried to solve it like you said, I keep reporting the error.
My code is as follows：
set.seed(100)
bootnet_case_dropping <- bootnet(network,nBoots=500,type="case",corMethod = "cor", corArgs = list(method = "spearman"),directed=T,caseN = 60, statistics=c("Closeness", "Betweenness", "Strength"), ncores=1)

报错：in bootnet_correlate(data = data, corMethod = corMethod, corArgs = corArgs,  : Correlation matrix is not positive definite.

**Comment by SachaEpskamp** [comment]
What is the sample size? Maybe try setting caseMax lower if your sample size is too smal. The argument `nCores` is not written correct here by the way. You also don't want to set `caseN = 60`, that is far too many for `nBoots=500`. Keep `caseN = 10`.

**Comment by ricardoo-cn** [comment]
Hi Sacha, My problem is that I used the following code for stability checking in R:
`network<-estimateNetwork(symptom,default = "EBICglasso",corMethod = "spearman")`
  
**The error message is**
Estimating Network. Using package::function:
  - qgraph::EBICglasso for EBIC model selection
    - using glasso::glasso
error at bootnet_correlate(data = data, corMethod = corMethod, corArgs = corArgs, : 
  Correlation matrix is not positive definite.
  
  At first, I thought the sample size might be less than the number of symptoms, but when I adjusted the number of symptoms (25) to be less than the sample size (26), the error still occurred, by the way, there were still a very small number of missing values in the total data. I understand that the relevant test requires a large number of samples, but as a preliminary experiment before the formal investigation, I still hope to get familiar with the use of software in this process. The results of a timely pre-survey may be biased.
 
  Thank you for your help.

**Comment by SachaEpskamp** [comment]
I am afraid that N = 26 is far too few datapoints to reliably estimate a 25 node netowrk. And indeed with missing data included this might create issues. You can get around this error using the methods described in https://github.com/SachaEpskamp/bootnet/issues/126, but I strongly recommend you do not do this.
