### ISSUE TITLE
bootnet error messages

### ISSUE THREAD

**Issue by ksm20** [SachaEpskamp/bootnet#42]
I’m using bootnet to estimate a network of ordinal, binary, and continuous variables.  Network estimation is fine as far as I can tell:

EDDS_net<-estimateNetwork(EDDS_complete, default = "mgm")

But I get a series of error messages when I attempt to bootstrap for centrality stability

> Boot_edds2 <- bootnet(EDDS_net, type = "case", nCores = 1, default = "mgm")

Bootstrapping...
Error in glmnetRequirements(data = data, type = type, weights = weights) : 
  Please only provide variables with nonzero variance. Variable(s) with zero variance: V14.
Error in glmnetRequirements(data = data, type = type, weights = weights) : 
  At least 2 events required for each category. Requirement not met for variable(s): NA
 Error in glmnetRequirements(data = data, type = type, weights = weights) : 
  Please only provide variables with nonzero variance. Variable(s) with zero variance: V14.
 Error in glmnetRequirements(data = data, type = type, weights = weights) : 
  At least 2 events required for each category. Requirement not met for variable(s): NA
Error in glmnetRequirements(data = data, type = type, weights = weights) : 
  Please only provide variables with nonzero variance. Variable(s) with zero variance: V14., V15.
Error in glmnetRequirements(data = data, type = type, weights = weights) : 
  At least 2 events required for each category. Requirement not met for variable(s): NA
Error in glmnetRequirements(data = data, type = type, weights = weights) : 
  Please only provide variables with nonzero variance. Variable(s) with zero variance: V14.
 Error in glmnetRequirements(data = data, type = type, weights = weights) : 
  At least 2 events required for each category. Requirement not met for variable(s): NA, NA

And so on.  It does finish running.  The errors may be at least party due to the fact that some of these variables measure behaviors that have a relatively low prevalence in community samples.  For example, variables 14 and 15:
> table(EDDS_complete$V14)

  0   1   2   3   4   5   8 
238   3   1   2   3   1   1

> table(EDDS_complete$V15)

  0   1   2   3   4   5   6   7  14 
233   4   5   2   1   1   1   1   1

Are these results valid, or should I combine some variables to address these error messages?

**Comment by SachaEpskamp** [comment]
You can't use mgm to model ordinal variables. Also, two things may go wrong here too: first you did not specify which variables are binary and which are continuous, and second perhaps there are cases with missing data (NA) dat get removed? mgm does listwise deletion so it can remove a lot of data some times.

**Comment by ksm20** [comment]
Thanks for your response.  I've been running this analysis with complete cases.  V14 and V15 are questions about the frequency of behaviors ("How many times per week on average over the past 3 months have you...?") 

I thought that bootnet/mgm was automatically detecting which variables were binary/continuous:

> EDDS_net<-estimateNetwork(EDDS_complete, default = "mgm")
Estimating Network. Using package::function:
  - mgm::mgm for network computation
    - Using glmnet::glmnet
'type' argument not assigned. Setting type to 'c' for all binary variables and 'g' for all other variables.
'level' argument not assigned. Setting level to 1 for all Gaussian/Poisson variables and number of unique values for all categorical variables

I do want to add another measure to this network to investigate bridge symptoms, which would mean modeling continuous, binary, and ordinal items.  What is the best method for doing this?

**Comment by SachaEpskamp** [comment]
Hi, Perhaps those items you want to treat as Poisson variables? Right, the bootnet wrapper does try to detect binary items indeed. 

Best, Sacha

**Comment by ksm20** [comment]
Thanks!  I can try that.  What would you recommend for my larger network with binary, continuous or count, and ordinal variables?

Karen

**Comment by SachaEpskamp** [comment]
Sorry for the late reply. There isn't really a right solution to this at the moment I am afraid. You can use MGM but not handle the ordinal variables properly, or use GGM estimation in any of the packages but not treat the binary and count variables properly...
