### ISSUE TITLE
Difficulties running bootnet when type is set to "case"

### ISSUE THREAD

**Issue by Gal-Laz** [SachaEpskamp/bootnet#43]
Hi Sacha,
I'm having difficulties running bootnet when type is set to "case" (no issues when type is set to "nonparametric").
The bootnet function is as follows:
bnet_case = bootnet(net4025,nBoots=100,nCores=1,type="case")
When I'm setting the nBoots to small numbers (<50) the function works fine (even though it takes a long time), but when I'm setting the nBoots to higher numbers R seems to stop in the middle. 
In the R Condole the last line is " Error in if (sum(abs(beta - beta_old)) < (convergence * sum(abs(beta_ridge)))) { : missing value where TRUE/FALSE needed

The estimateNetwork function is as follows: 
net4025 = estimateNetwork(Datasplit[["4025"]],default="graphicalVAR",tuning = 0, vars = labels, dayvar = "date",nLambda = 25).
The data are 9 variables time series of a single participant with 50 time points. 
Many thanks for the help!

Gal

**Comment by SachaEpskamp** [comment]
I think you are running into estimation problems with too little data. Perhaps you can set the `caseMax` argument lower?

**Comment by Gal-Laz** [comment]
It really worked!
Thank you so much!
