### ISSUE TITLE
"Error in checkForRemoteErrors(val)" appears when running bootnet.

### ISSUE THREAD

**Issue by Shen-Jianfei** [SachaEpskamp/bootnet#44]
Hi, Sacha
Recently, there appears a strange error when I running the bootnet. 
`bootnet_SAS <- bootnet(Data_SAS,
                                nBoots = 10000,
                                default = "EBICglasso",
                                tuning = 0.5,
                                type = "nonparametric",
                                statistics = c("edge","strength","closeness","betweenness"),
                                nCores = 2)`
When I ran the above code in R (v.3.5.2) with package bootnet (v.1.1.0) on my old computer, it worked very well. Recently, I ran the above code on my new computer installed with R (v.3.6.3) and bootnet (v1.1.0), it cannot work and returned the following message:

> Note: bootnet will store only the following statistics:  edge, strength, closeness, betweenness
> Estimating sample network...
> Estimating Network. Using package::function:
>   - qgraph::EBICglasso for EBIC model selection
>     - using glasso::glasso
>   - qgraph::cor_auto for correlation computation
>     - using lavaan::lavCor
> Variables detected as ordinal: A1; A2; A3; A4; A5; A6; A7; A8; A9; A10; A11; A12; A13; A14; A15; A16; A17; A18; A19; A20
> Bootstrapping...
>   |                                                  | 0 % ~calculating  Error in checkForRemoteErrors(val) : 
>   one node produced an error: Maximum number of errors in bootstraps reached
> Warning message:
> In EBICglassoCore(S = S, n = n, gamma = gamma, penalize.diagonal = penalize.diagonal,  :
>   A dense regularized network was selected (lambda < 0.1 * lambda.max). Recent work indicates a possible drop in specificity. Interpret the presence of the smallest edges with care. Setting threshold = TRUE will enforce higher specificity, at the cost of sensitivity.

This error "**Error in checkForRemoteErrors(val) : 
  one node produced an error: Maximum number of errors in bootstraps reached**" may stop the process of bootnet.
Then, I updated the package bootnet to version 1.3, however, the same error still appeared. The data is a dataset which has 20 variables and 218 cases. It really confused me. Thank you very much for your help to solve this error!
Sincerely,
Shen Jianfei.

**Comment by SachaEpskamp** [comment]
Hi Shen,

This is not really the way bootnet is supposed to be used. Please first use estimateNetwork:
```
net <- estimateNetwork(Data_SAS,  default = "EBICglasso", tuning = 0.5)
bootnet_SAS <- bootnet(net , nBoots = 10000, type = "nonparametric", statistics = c("edge","strength","closeness","betweenness"), nCores = 2)
```
This may solve the problem. If not, please use `nCores = 1` and see if you get a more informative error message (the current message simply says that something went wrong in the multi-core process).

**Comment by Shen-Jianfei** [comment]
Thanks very much for your response! 
I tried the codes recommended in your reply. Unfortunately, the same error still existed. After I used `nCores = 1` instead of `nCores = 2`, R returned the imformation including a series of errors which is just like below:

> Note: bootnet will store only the following statistics:  edge, strength, closeness, betweenness
> Estimating sample network...
> Estimating Network. Using package::function:
>   - qgraph::EBICglasso for EBIC model selection
>     - using glasso::glasso
>   - qgraph::cor_auto for correlation computation
>     - using lavaan::lavCor
> Variables detected as ordinal: A1; A2; A3; A4; A5; A6; A7; A8; A9; A10; A11; A12; A13; A14; A15; A16; A17; A18; A19; A20
> Bootstrapping...
>   |                                                                                                               |   0%Error in bootnet_correlate(data = data, corMethod = corMethod, corArgs = corArgs,  : 
>   Correlation matrix is not positive definite.
> Warning message:
> In EBICglassoCore(S = S, n = n, gamma = gamma, penalize.diagonal = penalize.diagonal,  :
>   A dense regularized network was selected (lambda < 0.1 * lambda.max). Recent work indicates a possible drop in specificity. Interpret the presence of the smallest edges with care. Setting threshold = TRUE will enforce higher specificity, at the cost of sensitivity.
> Error in bootnet_correlate(data = data, corMethod = corMethod, corArgs = corArgs,  : 
>   Correlation matrix is not positive definite.
> Error in bootnet_correlate(data = data, corMethod = corMethod, corArgs = corArgs,  : 
>   Correlation matrix is not positive definite.
> Error in bootnet_correlate(data = data, corMethod = corMethod, corArgs = corArgs,  : 
>   Correlation matrix is not positive definite.
> Error in bootnet_correlate(data = data, corMethod = corMethod, corArgs = corArgs,  : 
>   Correlation matrix is not positive definite.
> Error in bootnet_correlate(data = data, corMethod = corMethod, corArgs = corArgs,  : 
>   Correlation matrix is not positive definite.
> Error in bootnet_correlate(data = data, corMethod = corMethod, corArgs = corArgs,  : 
>   Correlation matrix is not positive definite.
> Error in bootnet_correlate(data = data, corMethod = corMethod, corArgs = corArgs,  : 
>   Correlation matrix is not positive definite.
> Error in bootnet_correlate(data = data, corMethod = corMethod, corArgs = corArgs,  : 
>   Correlation matrix is not positive definite.
> Error in bootnet_correlate(data = data, corMethod = corMethod, corArgs = corArgs,  : 
>   Correlation matrix is not positive definite.
> Error in bootnet_correlate(data = data, corMethod = corMethod, corArgs = corArgs,  : 
>   Correlation matrix is not positive definite.
> Error in bootnet_correlate(data = data, corMethod = corMethod, corArgs = corArgs,  : 
>   Correlation matrix is not positive definite.
> Error in bootnet(net, nBoots = 1000, type = "nonparametric", statistics = c("edge",  : 
>   Maximum number of errors in bootstraps reached

It seems that there is something wrong in the correlation matrix calculated from the dataset. But the same correlation matrix can be used correctly by bootnet on my old computer. So I am very confused about the error information. Many thanks and looking forward to hearing from you!
Sincerely,
Shen Jianfei.

**Comment by SachaEpskamp** [comment]
This is likely due to polychoric correlations being unstable. Try `corMethod = "spearman"` instead.

**Comment by Shen-Jianfei** [comment]
Many thanks for your reply!
After I added `corMethod = "spearman"`, the bootnet ran correctly!!! I am very grateful for your kind help!
Sincerely,
Shen Jianfei.

**Comment by YRasch** [comment]
Hello Sacha,
thank you for all your work and output regarding psychological network models! I have the same Problem. I have plotted a polychloric partial correlation network of 90 SCL-90 items (5-point-likert scale) with n=1506 using 

> _V5_Netzwerk_boot <- estimateNetwork(v5_final, default = "EBICglasso", cormethod = "cor_auto")._ 

This works fine. Also the casedrop bootstrapping worked fine, using the function 

> _bootnet(V5_Netzwerk_boot, nBoots = 2500, nCores = 8, type ="case")_

I have the value 0.594 for both strength and edge, so I figured it was stable enough regardless of the pretty "heavy" network containing 90 nodes. Nonethelesss, running 

> _bootnet(V5_Netzwerk_boot, nBoots = 1000, nCores =8)_ 

does produce the same Error Shen-Jianfai described above. I tried 

> _bootnet(V5_Netzwerk_boot, nBoots = 1000, corMethod="spearman", nCores =8)_

and also  

> _bootnet(V5_Netzwerk_boot, nBoots = 1000, nonPositiveDefinite = "continue", nCores =8)_

to try if it really is just the matrix being not positive definite, even if the functions beforehand worked perfectly fine. Also restarting R didn't solve the issue :-)
Is there anything else I can try to solve the problem? 

Kind regards
Yvonne Rasch

**Comment by SachaEpskamp** [comment]
Hi Yvonne,

You have to put corMethod = "spearman" in the estimateNetwork call, not in the bootnet call. It should work then.

Best, Sacha

**Comment by YRasch** [comment]
Hi Sacha,
thank you for your quick response. 
Unfortunately the network created with

> _V5_Netzwerk_boot_spearman <- bootnet::estimateNetwork(V5_Matrix, default="EBICglasso", corMethod ="spearman")_

with bootstrap code

> _V5_boot_casedrop_sp <- bootnet(V5_Netzwerk_boot_spearman, nBoots = 1000, nCores = 8, type ="case")_

yields the same error. 

V5_Matrix, which I use above, is a correlation-matrix estimated with cor_auto (detect ordinal = true & ordinalLevelMax=5).
If I use the original dataset (w/o missings, imputed with predictive mean matching) or a correlation-matrix calculated with cor() and spearman correlations as input computing a network yields the error cormat is not posdef. 

It was possible to bootstrap the edgeweights with the polychloric estimated network once I reduced the nboot to 100 and 200 though. There was no big difference according to visual analysis of the edgeplot and the CIs did not seem to be broad. If thats fine - I would be good?

Independently, after calculating the nBoot(200) the

_

> plot(v5_boot_all_edgeweight, "edge", plot ="difference", order = "sample")

_ 

responds with the error "rep.int(seq_len(nx), rep.int(rep.fac, nx)) : invalid 'times' value. 
I'm guessing the file is just too big. Is there a possibility to only plot a subset of nodes? as only a subset is relevant for me. 

Best
Yvonne

**Comment by SachaEpskamp** [comment]
Hi Yvonne,

The input to `estimateNetwork` must be raw data not a correlation matrix.

Best, Sacha

**Comment by lxxhy** [comment]
Hi Sacha,

I want to ask you a question because I have a similar problem as above.
At first, I put the code as below, and I changed it to the second code according to your advice.

`boots <- bootnet(Network, statistics = c("Strength", "Closeness", "Betweenness"), nBoots = 1000, nCores = 4, type = "case")`

> Note: bootnet will store only the following statistics:  Strength, Closeness, Betweenness
> Estimating sample network...
> Estimating Network. Using package::function:
>   - qgraph::EBICglasso for EBIC model selection
>     - using glasso::glasso
>   - qgraph::cor_auto for correlation computation
>     - using lavaan::lavCor
> Variables detected as ordinal: D1; D2; D3; D4; D5; D6; D7; D8; D9; D10; D11; D12; D13; D14; D15; D16; D17; D18; D19; D20; D21; A1; A2; A3; A4; A5; A6; A7; A8; A9; A10; A11; A12; A13; A14; A15; A16; A17; A18; A19; A20; A21
> Bootstrapping...
>   |++++++++++++++++++                                | 35% ~28m 06s      Error in checkForRemoteErrors(val) : 
>   one node produced an error: Maximum number of errors in bootstraps reached
> Warning message:
> In EBICglassoCore(S = S, n = n, gamma = gamma, penalize.diagonal = penalize.diagonal,  :
>   A dense regularized network was selected (lambda < 0.1 * lambda.max). Recent work indicates a possible drop in specificity. Interpret the presence of the smallest edges with care. Setting threshold = TRUE will enforce higher specificity, at the cost of sensitivity.

`boots <- bootnet(Network, statistics = c("Strength", "Closeness", "Betweenness"), nBoots = 1000, nCores = 1, corMethod = "spearman", type = "case")`

Then I got this error.

> > Note: bootnet will store only the following statistics:  Strength, Closeness, Betweenness
> Estimating sample network...
> Estimating Network. Using package::function:
>   - qgraph::EBICglasso for EBIC model selection
>     - using glasso::glasso
>   - qgraph::cor_auto for correlation computation
>     - using lavaan::lavCor
> Variables detected as ordinal: D1; D2; D3; D4; D5; D6; D7; D8; D9; D10; D11; D12; D13; D14; D15; D16; D17; D18; D19; D20; D21; A1; A2; A3; A4; A5; A6; A7; A8; A9; A10; A11; A12; A13; A14; A15; A16; A17; A18; A19; A20; A21
> Bootstrapping...
>   |                                                                           |   0%Error in bootnet_correlate(data = data, corMethod = corMethod, corArgs = corArgs,  : 
>   Correlation matrix is not positive definite.
> Warning message:
> In EBICglassoCore(S = S, n = n, gamma = gamma, penalize.diagonal = penalize.diagonal,  :
>   A dense regularized network was selected (lambda < 0.1 * lambda.max). Recent work indicates a possible drop in specificity. Interpret the presence of the smallest edges with care. Setting threshold = TRUE will enforce higher specificity, at the cost of sensitivity.

I would really appreciate it if you could let me know if there are other possible attempts to resolve this error.

**Comment by Yanghuiting2000** [comment]
Hi Sacha,

I want to ask you a question because I have a similar problem as above.
At first, I put the code as below:
CLPN.OR <- function(data) {
  adjMatCovCLPN <- matrix(0, k+numCovar, k+numCovar) 
  for (i in 1:k) {
    lassoreg <- cv.glmnet(x=as.matrix(data[,c(1:k,(k*2+1):(k*2+numCovar))]), 
                          y=data[,(k+i)], 
                          nfolds=10, family="binomial", alpha=1, standardize=TRUE, parallel=TRUE)
    lambda <- lassoreg$lambda.min
    adjMatCovCLPN[1:(k+numCovar),i] <- coef(lassoreg, s=lambda, exact=FALSE)[2:(k+numCovar+1)]
  }
  adjMatCLPN <- adjMatCovCLPN[1:k, 1:k]
  ## Convert from logit/log odds to odds ratios
  adjMatCLPN.OR <- exp(adjMatCLPN)
  return(adjMatCLPN.OR)
}

## Estimate networks in bootnet (for bootstrapping)
net.6_12 <- estimateNetwork(myData, fun=CLPN.OR, labels=labels, directed=TRUE)
nonParBoot.6_12 <- bootnet(net.6_12, type="nonparametric", nBoots=1500, communities=groups, directed=TRUE,
                           statistics=c("edge","outExpectedInfluence","inExpectedInfluence","bridgeExpectedInfluence"),
                           nCores=4)

Then I got this error:
Note: bootnet will store only the following statistics:  edge, outExpectedInfluence, inExpectedInfluence, bridgeExpectedInfluence
Bootstrapping...
  |                                                  | 0 % ~calculating  Error in checkForRemoteErrors(val) : 
  7 nodes produced errors; first error: Maximum number of errors in bootstraps reached

I would really appreciate it if you could let me know if there are possible attempts to resolve this error.

**Comment by Yanghuiting2000** [comment]
Hi Sacha,

I want to ask you a question because I have a similar problem as above.
At first, I put the code as below:
CLPN.OR <- function(data) {
adjMatCovCLPN <- matrix(0, k+numCovar, k+numCovar)
for (i in 1:k) {
lassoreg <- cv.glmnet(x=as.matrix(data[,c(1:k,(k2+1):(k2+numCovar))]),
y=data[,(k+i)],
nfolds=10, family="binomial", alpha=1, standardize=TRUE, parallel=TRUE)
lambda <- lassoreg$lambda.min
adjMatCovCLPN[1:(k+numCovar),i] <- coef(lassoreg, s=lambda, exact=FALSE)[2:(k+numCovar+1)]
}
adjMatCLPN <- adjMatCovCLPN[1:k, 1:k]
adjMatCLPN.OR <- exp(adjMatCLPN)
return(adjMatCLPN.OR)
}

net.6_12 <- estimateNetwork(myData, fun=CLPN.OR, labels=labels, directed=TRUE)
nonParBoot.6_12 <- bootnet(net.6_12, type="nonparametric", nBoots=1500, communities=groups, directed=TRUE,
statistics=c("edge","outExpectedInfluence","inExpectedInfluence","bridgeExpectedInfluence"),
nCores=4)

Then I got this error:
Note: bootnet will store only the following statistics: edge, outExpectedInfluence, inExpectedInfluence, bridgeExpectedInfluence
Bootstrapping...
| | 0 % ~calculating Error in checkForRemoteErrors(val) :
7 nodes produced errors; first error: Maximum number of errors in bootstraps reached

I would really appreciate it if you could let me know if there are possible attempts to resolve this error.

**Comment by SachaEpskamp** [comment]
Hi! You need to put the packages you use also int he custom function if you plan to use multi-core bootstrapping. in this case, I think `library("lme4")`?
