### ISSUE TITLE
Error in binarize()

### ISSUE THREAD

**Issue by atomashevic** [SachaEpskamp/bootnet#46]
Hi,

I think there is an error with binarize() function.

```
for (i in seq_len(ncol(x))) {
            x[, i] <- 1 * (x[, i] < splits[i])
        }
```
So if split[i]=2 and for example x[1,1]=1 since 1<2 is true, return value is 1 (and it should be 0 since x[1,1] is less than split value).

**Comment by SachaEpskamp** [comment]
You are right. Thanks! I updated this now in the package.

Note: it shouldn't actually matter for the resulting Ising network if you encode 0-1 or 1-0, but of course this makes more sense.
