### ISSUE TITLE
default = "adalasso" error

### ISSUE THREAD

**Issue by TijanaKaric** [SachaEpskamp/bootnet#47]
Hi Sacha,

I am trying to use estimateNetwork: network <- estimateNetwork(Data, default = "adalasso"), but I get this message: 
Error in (function (data, missing = c("listwise", "stop"), verbose = TRUE,  : 
  Adaptive LASSO default set is currently not supported due to CRAN removal of 'parcor' package.

Could you please help me with further steps? Or am I doing something wrong?

Thank you,
Tijana

**Comment by SachaEpskamp** [comment]
Hi Tijana,

As the error message says, the 'parcor' package was removed from CRAN, which included the adaptive LASSO. This means you cannot use this functionality anymore.

Best, Sacha

**Comment by TijanaKaric** [comment]
Hi Sacha,

Yes, I understand that, but how am I supposed to estimate network then? :) Is it even possible anymore?

Best,
Tijana

**Comment by SachaEpskamp** [comment]
Just use any of the other default sets? Such as default = "ggmModSelect"? The adaptive lasso was hardly used anyway.

Best, Sacha

**Comment by TijanaKaric** [comment]
Thank you!
