### ISSUE TITLE
Problem with Bootstrapping "Error in makePSOCKcluster(nClust)"

### ISSUE THREAD

**Issue by shrutisram** [SachaEpskamp/bootnet#48]
I am having an issue with bootstrapping, and I wanted to reach out for your advice. I am attempting to run a network analysis. I have used this code before, and it works fine, until I attempt to bootstrap for stability analyses. Then I get the following error message:

Bootstrapping...
Error in makePSOCKcluster(nClust) :
  Cluster setup failed. 3 of 3 workers failed to connect.
In addition: Warning message:
In EBICglassoCore(S = S, n = n, gamma = gamma, penalize.diagonal = penalize.diagonal,  :
  A dense regularized network was selected (lambda < 0.1 * lambda.max). Recent work indicates a possible drop in specificity. Interpret the presence of the smallest edges with care. Setting threshold = TRUE will enforce higher specificity, at the cost of sensitivity.

Any ideas on how to fix this? I am using Max OSX Catalina, R version 4.0 and R Studio Version 1.3.959.

**Comment by SachaEpskamp** [comment]
Hi Shruti,

Perhaps you are trying to use more cores than your computer supports?
Try first with nCores = 1 to see if it works.

Best, Sacha

**Comment by SachaEpskamp** [comment]
I think this is fixed in devel version now.
