### ISSUE TITLE
Problem with using custom function in bootnet()

### ISSUE THREAD

**Issue by mjbsp** [SachaEpskamp/bootnet#5]
I would like to use a custom network estimation function with bootnet(). 

I first define by custom function. This is just a simple correlation matrix for sake of example.

```R
cortest <- function(x){
  require(qgraph)
  cor_net <- cor_auto(x, 
                      detectOrdinal = T, ordinalLevelMax = 7, 
                      missing = "fiml")
  return(cor_net)
}
```

I can estimate a network using estimateNetwork(). This has no problems.

```R
net <- estimateNetwork(dat, fun = cortest)
```

However, if I try to use bootnet() to estimate this network and estimate stability etc, I run into errors. Here is my code (nBoots = 10 as I test my code)

```R
boots <- bootnet(dat, fun = cortest, type = "parametric", nBoots = 10)

``` 

And here is my error message.

> Error in checkInput(default = default, fun = fun, prepFun = prepFun, prepArgs = prepArgs,  : 
>   If 'default' is not set and 'fun' is missing, 'prepFun', 'prepArgs', 'estFun' and 'estArgs' may not be missing.

I have tried setting default to "none", but received the same error message. 

Thanks for any help.

**Comment by SachaEpskamp** [comment]
Hi,

I think the parametric bootstrap will not work using this input no matter what because bootnet does not know how to simulate data from your network. The intended use is to first estimate your network in estimateNetwork and then use that input in bootnet, which works:

```
library(bootnet)
library(psych)
data(bfi)

cortest <- function(x){
  require(qgraph)
  cor_net <- cor_auto(x, 
                      detectOrdinal = T, ordinalLevelMax = 7, 
                      missing = "fiml")
  return(cor_net)
}


net <- estimateNetwork(bfi[,1:25], fun = cortest)

boots <- bootnet(net, type = "nonparametric", nBoots = 10)
```

I just noticed a bug not allowing for bootnet() to be used with a custom function, which I fixed now on the Github version, thanks for reporting! This should now work too:
`
boots <- bootnet(bfi[,1:25], fun = cortest, type = "nonparametric", nBoots = 10)
`

**Comment by mjbsp** [comment]
Thanks. This works. I didn't realize that it was possible to put an estimateNetwork object into bootnet. Very helpful.

**Comment by lindoyle** [comment]
Hello, I have a similar problem. I am trying to estimate with the TMFG method from the package NetworkToolbox. 
Following the above advice,  I created a tmfgest function and used that to estimate the network. And then used nonparametric bootstrapping. This all works fine. (also using nBoots = 10 to test the code.)
```
tmfgest <- function(x){
  cor_net <- cor_auto(x,
                      detectOrdinal = T, ordinalLevelMax = 7, 
                      forcePD = T, missing = "pairwise")
  matrix <- TMFG(cor_net)
  return(matrix$A)
}

net <- estimateNetwork(dat, fun = tmfgest)
boot <- bootnet(net, fun = tmfgest, type = "nonparametric", nBoots = 10)
```
Then I try to do the same with subsetting (i.e., type = "case") 
```
sub3 <- bootnet(net3,nBoots = 10,fun = tmfgest,nCores = 8,type="case")
```
But I get this error
```
Error in checkForRemoteErrors(val) : 
  7 nodes produced errors; first error: Maximum number of errors in bootstraps reached
```
Any suggestions would be be much appreciated.

**Comment by SachaEpskamp** [comment]
Hi Lindoyle,

When using multiple cores you need to load all relevant packages within the function. I think it should work if you add `library("NetworkToolbox")` in the function.

Best, Sacha

**Comment by lindoyle** [comment]
Ok, thanks!

**Comment by kathku** [comment]
Hi, 
I have just the same problem using the bootnet function for a network. I have installed all relevant packages (only psychTools for some reason does not work - could this one package be the problem?)

net1 <- estimateNetwork(df, 
                                 default = "ggmModSelect",
                                 stepwise = TRUE,
                                 corMethod = "cor")

boot1 <- bootnet(net1, nBoots = 100, nCores = 8)

I get the following error message: 
  7 nodes produced errors; first error: Maximum number of errors in bootstraps reached


When I decrease the cores to 4 or 2, the error message reports 3 or 1 node that produced an error. 


It would be great if someone had any ideas on how to solve this. 

Best, 
Katharina

**Comment by SachaEpskamp** [comment]
HI Katharina,

Does net1 give you a valid object with an estimated network? And what error do you get when setting `nCores = 1` (it should be different than setting it larger than 1)?

**Comment by kathku** [comment]
Hi Sacha, 
yes, net1 is a valid network object. 
With ncores=1 (which is the same as leaving it out?) and nboots = 5 the code works. Would a solution be to just let the computer do the work over a longer time with more bootstraps?

**Comment by pevitr** [comment]
Hi,
I'm having an issue similar to the problems above.
Currently running a network using a sample of ~730 youth. 
The dataset is complete and items with no variability have been removed.

I am attempting to run bootnet for stability analyses but am getting the following error code when running my bootstrapping analyses:
"Error in checkForRemoteErrors(val) : 
  one node produced an error: Maximum number of errors in bootstraps reached"

Here is the code I have been using for network analyses.
mynames <- c("bully", "PhysFight", "Weapon", "CruelPpl", "CruelAni", "StolenVic", "Force",
             "Fire", "Vandal", "Lie", "Shoplift", "Curfew")

Network<-estimateNetwork(MyDataCH.12, default = "EBICglasso", tuning = .5, labels = colnames(MyDataCH.12))

plot(Network, layout = "spring", vsize=6, color="lightblue", border.color="black", 
     nodeNames=mynames, legend=TRUE)

setwd("C:/Users/pevit/OneDrive/Pevitr/All Work & Research/UK/UK RISK Lab Research/Research Projects/Preschool_Childhood Projects/CD Network/Data/Excel/ChildhoodFull Y1")
pdf("Y1 ChildhoodFull CD_Network1.pdf")
myplot <- plot(Network, layout = "spring", vsize=6, color="lightblue", border.color="black")
dev.off()

library("NetworkToolbox")

b1 <- bootnet(Network, boots=1000, nCores = 4, statistics = c("strength", "expectedInfluence", "edge"))
b2 <- bootnet(Network, boots=1000, nCores = 4, type = "case", statistics = c("strength", "expectedInfluence", "edge"))

Thanks much!

**Comment by LauMalMur** [comment]
> Hi Sacha, yes, net1 is a valid network object. With ncores=1 (which is the same as leaving it out?) and nboots = 5 the code works. Would a solution be to just let the computer do the work over a longer time with more bootstraps?

I have the same problem. Is any solution found?

**Comment by XUNBAOBAO** [comment]
Hi ,
I'm having an issue similar to the problems above.
I am attempting to run bootnet for correlation stability analyses but am getting the following error code when running it:
"Note: bootnet will store only the following statistics:  edge, strength, outStrength, inStrength"
Error in data[, goodColumns, drop = FALSE] : Wrong number of measurements
in addition, Warning message:
In bootnet(Network1, nboots = 3000, type = "case", nCores = 8, statistics = c("edge",  :
  Removing non-numeric columns: 1; 2; 3; 4
I do not know how to solve it.
actually，i have built the network1(about two groups, 12items(Agroup=1-9, Bgroup=10-12),560 subjects)
Any suggestions would be be much appreciated.
