### ISSUE TITLE
Estimating mgm on items on different scales

### ISSUE THREAD

**Issue by hcuve** [SachaEpskamp/bootnet#52]
This is not necessarily an issue, and it's more of a question, but couldn't find a forum where to ask this, so please feel free to close this.

I am wondering if there are any considerations on estimating mgm networks on items with different response scales. Say a group of items with likert ratings from 1-4 and another set of items with 1 to 5 ratings.

My intuition is that I can combine those to estimate a joint network and that this should be fine, since the networks are based on correlations (or partial correlations). But wondering if there are any considerations I am missing.

Thanks you

Helio

**Comment by SachaEpskamp** [comment]
Hi, you cannot use mgm for such ordinal responses. You can either treat them as continuous, or use another method. See our summer school videos for more information: http://psychosystems.org/NetworkSchool.

Best, Sacha

**Comment by hcuve** [comment]
Thank you @SachaEpskamp 

I actually meant to ask about estimating these items together in the same network while treating them as continuous (the mgm was a mixup from my side). 
Thank you

**Comment by SachaEpskamp** [comment]
That should be fine.

Best, Sacha
