### ISSUE TITLE
Error in bootnet(default = "mgm") - specifying "type" argument

### ISSUE THREAD

**Issue by diegogaldinof** [SachaEpskamp/bootnet#55]
Hi, Sacha! How are you?

I'm having a problem with the bootnet function when I try to compute bootstrapped confidence intervals for MGM. Both the mgm and bootnet have an argument called "type" and they are overlapping.

`boot1 <- bootnet(data = dataset1, 
                                                   nBoots = 1000,
                                                   default = "mgm",
                                                   type = mgm_type,
                                                   level = mgm_level,
                                                   criterion = "EBIC",
                                                   tuning = 0.5,
                                                   rule = "AND",
                                                   binarySign = TRUE,
                                                   weights = w)`

Am I doing it right? Best regards!

Diego

**Comment by diegogaldinof** [comment]
Sorry, I found a way to resolve this. Beginner error.

**Comment by bernard-liew** [comment]
> Hi @ diegogaldinof, 

Experienced the same issue, what was your solution? Many thanks.

Regards,
Bernard

**Comment by diegogaldinof** [comment]
Hello, Bernard!
Instead of trying to run the mgm inside the bootnet function, I ran the network structure with the estimateNetwork function and put the output into the bootnet function. Something like that:

net <- estimateNetwork(data = my_data, default = "mgm", ...)
boot <- bootnet(net, nBoots = 1000, ...)

I'm reading the package documentation and the data argument of the bootnet function is a little confusing. It says: "A data frame or matrix containing the raw data". But, it is working with the estimateNetwork output. So, perhaps it would be easier to understand if it was added "or the output of the estimateNetwork function". What do you think, Bernard?

Best,
Diego.
