### ISSUE TITLE
A question about stability estimation

### ISSUE THREAD

**Issue by threetree-wu** [SachaEpskamp/bootnet#58]
Hi，I have just recently started learning the R. When I tried to use the bootnet to estimate the centrality stablity, I get an error"Network with lowest lambda selected as best network: assumption of sparsity might be violated.
Note: Network with lowest lambda selected as best network: assumption of sparsity might be violated."
After that I found that it could only trace out a single strength line.
Any help would be greatly appreciated!

`library("bootnet")
network <- estimateNetwork(data, default = "EBICglasso")
boot1=bootnet(network) # bootstrapping-edge-weight-accuracy
plot(boot1, labels = FALSE, order = "sample")
boot2=bootnet(network, type = "case") # centrality_stablity
plot(boot2)
corStability(boot2) # C-S Coefficients
differenceTest(boot1, 3, 1, "strength")  # testing for significant differences
plot(boot1, "strength")`

**Comment by SachaEpskamp** [comment]
Hi, that is not an error but a warning on the estimator. Depending on your data perhaps another estimator than the EBICglasso might be appropriate (e.g., ggmModSelect if you have few nodes and a high sample size). To get closeness and betweenness you have to use the statistics argument in bootnet() and plot().

**Comment by threetree-wu** [comment]
Thank you for your prompt reply！
I've used the statistics argument to make the closeness and betweenness，but when I use this `boot2=bootnet(network, type = "case", statistics="strength"，"closeness"， "betweenness"` .I can't put strength, closeness and betweenness in the same picture. It still only shows one line.

**Comment by SachaEpskamp** [comment]
In this syntax, you do not assign a vector to `statistics`. This should work:

```
boots <- bootnet(network, type = "case", statistics= c("strength"，"closeness"， "betweenness"))
plot(boots, statistics= c("strength"，"closeness"， "betweenness"))

```

**Comment by threetree-wu** [comment]
Thank you very much for your careful answer. I have completed it under your guidance
