### ISSUE TITLE
Centrality stability

### ISSUE THREAD

**Issue by Alba123-hu** [SachaEpskamp/bootnet#59]
Hi, Sacha

I am having problems when getting a single plot for the stability of centrality indices. More precisely, I cannot get one single plot for all the centrality indicators. Any idea?: Many thanks in advance,

boot2 <- bootnet(network , nBoots = 10000, type = "nonparametric", statistics = c("edge","strength","closeness","betweenness"), nCores = 2)
plot(boot2)

**Comment by diegogaldinof** [comment]
Hello, @Alba123-hu!
I think the most appropriate method to see the stability of centrality indices is `type = "case"`. But, if you are interested in the _differences_ between each node centrality, then you can use the `statistics =` argument inside the plot function.

boot2 <- bootnet(network , nBoots = 10000, type = "nonparametric", statistics = c("edge","strength","closeness","betweenness"), nCores = 2)
plot(boot2, statistics = "strength")

Best regards!

**Comment by Alba123-hu** [comment]
> Hello, @Alba123-hu!
> I think the most appropriate method to see the stability of centrality indices is `type = "case"`. But, if you are interested in the _differences_ between each node centrality, then you can use the `statistics =` argument inside the plot function.
> 
> boot2 <- bootnet(network , nBoots = 10000, type = "nonparametric", statistics = c("edge","strength","closeness","betweenness"), nCores = 2)
> plot(boot2, statistics = "strength")
> 
> Best regards!

Thank you very much! The issue now is that I cannot get a plot with all the centrality indicators. I've tried including all in the statistics statement, but nothing changed...I always get one for strength

Alba.

**Comment by diegogaldinof** [comment]
But your argument `type` is `"nonparametric"` or `"case"`? If `"nonparametric"`, maybe you will need to plot one plot each time. Otherwise, try to remove the `"edge"` in `statistics`, like this:

boot2 <- bootnet(network , nBoots = 10000, type = "case", statistics = c("strength","closeness","betweenness"), nCores = 2)
plot(boot2, statistics = "all")

Please, let me know if it worked.

Diego.

**Comment by SachaEpskamp** [comment]
Thanks for answering Diego! I think your answer should work!

**Comment by Alba123-hu** [comment]
Thank you! It worked!

Alba

**Comment by diegogaldinof** [comment]
Great!
