### ISSUE TITLE
summary bootnet

### ISSUE THREAD

**Issue by AdvaSegal** [SachaEpskamp/bootnet#6]
Hi,

I would like to ask how can I view the summarized table that is received in the output of the bootnet function in a full presentation or/and with Excel?

Attached is an image to illustrate my question.
![picture1](https://user-images.githubusercontent.com/36364699/36072799-048196c0-0f2f-11e8-8dde-51dc1a7a5960.png)

Thank you for your help.
Adva

**Comment by SachaEpskamp** [comment]
Try using the `as.data.frame` or (in RStudio) `View` function on the object. A tibble is just a data frame that by defaults only prints the first 10 rows. You can also just export it to a csv with `write.csv` and open in Excel.
