### ISSUE TITLE
Error in `type = "case"` bootstrapping with weighted MGM

### ISSUE THREAD

**Issue by diegogaldinof** [SachaEpskamp/bootnet#60]
Hello, Sacha!

I'm having an issue when I try to bootstrap my weighted MGM in order to analyze the stability of the centrality indices. I have a weights vector that is separated from the dataset. When I estimate the mgm, everything goes well. But, when I applied the bootnet function with the `type = "case"`, an error is returned: "Number of observations is not equal to length of weights vector."

net <- bootnet::estimateNetwork(data, default = "mgm",
                                       criterion = "EBIC", tuning = 0.25,
                                       type = type, level = level, rule = "AND",
                                       binarySign = TRUE, weights = my_weights, weighted = TRUE)

boot <- bootnet::bootnet(net, nBoots = 2,
                           type = "case", nCores = 1,
                           statistics = c("strength", "ExpectedInfluence"))

Is this happening because when the bootnet starts the case-dropping, it subsamples just the dataset and not the weights vector?
I'm using R 4.0.3 and RStudio 1.3.1. Bootnet is 1.4.3.

Thanks for your attention!

Best regards!

**Comment by SachaEpskamp** [comment]
Hi Diego,

Thanks for this. I am not familiar with the weighing function of mgm so perhaps something goes wrong there. Could you please provide a small reproducible example with a small dummy dataset?

Best, Sacha

**Comment by diegogaldinof** [comment]
Hello, Sacha! Sure, here is the example:

library(mgm); library(bootnet)
data("dataGD")
dataGD <- as.data.frame(dataGD)[1:200, 1:5] # just 200 rows and 5 columns
weig <- rnorm(200, 1, 0.05) # weights vector
type <- c("g", "g", "c", "g", "c")
level <- c(1, 1, 2, 1, 3)
net <- estimateNetwork(dataGD, default = "mgm", type = type, level = level, rule = "AND",
criterion = "EBIC", binarySign = TRUE,
tuning = 0.25, weighted = TRUE, weights = weig)

boot1 <- bootnet(net, nBoots = 10, type = "case", nCores = 1, statistics = c("strength", "ExpectedInfluence")) # gives the error

And what pops up is:
"Error in mgm::mgm(data, verbatim = !verbose, warnings = verbose, signInfo = FALSE, 
Number of observations is not equal to length of weights vector."

Thank you again, Sacha!

Best, Diego.

**Comment by SachaEpskamp** [comment]
Ah I see. The problem is that the `weights` vector gives a weight per case, but with the case-drop bootstrap you sub-sample cases, meaning you get a different number of cases. With the non-parametric you don't get an error but you would still get weird results because the weights would not be mapped correctly to the re-sampled cases. This is not something easy to solve at the moment in `bootnet`, as the underlying infrastructure isn't really supporting this... Perhaps you could consider using the bootstrap methods built into the `mgm` package?

**Comment by diegogaldinof** [comment]
oh, it’s true, I didn’t notice this problem either. No problem, I can try to do the analysis with mgm :: resample. I was thinking that to solve this problem I would just need to find a way to: a) join the weight vector with the dataset; b) resampling; c) remove the weight vector from the dataset and save it to an object; d) estimate the network; e) repeat the process. But it doesn't seem to be something like that, does it?
Best, Diego.

**Comment by SachaEpskamp** [comment]
Hi Diego,

This could work if you not use `default = "mgm"` but rather use the `fun` argument to define your own function. Then you could just take the weights column out in your custom function and use it in the mgm call.

Best, Sacha

**Comment by diegogaldinof** [comment]
Got it, Sacha! Thank you very much for your tips and support.

Best, Diego
