### ISSUE TITLE
case-dropping subset bootstrap not producing requested centrality statistics

### ISSUE THREAD

**Issue by etampke** [SachaEpskamp/bootnet#61]
Hi there, I'm not sure if this is the proper place to be asking this question.

I am having an issue with the case-dropping subset bootstrap function. I have been following the code outlined in Epskamp, Borsboom, and Fried (2018), but I am not getting similar parameters in my results. I am wondering if there is something wrong with my code?

TAD2case <- bootnet(TeachAggData, type ="case", statistics = c("strength","closeness", "betweenness"))
plot (TAD2case)

The resulting plot only include the strength index. 
<img width="589" alt="Sample of problem" src="https://user-images.githubusercontent.com/78666780/107161110-0cf39900-6960-11eb-8c23-5a29641247d2.png">

**Comment by SachaEpskamp** [comment]
You also need to include `statistics = c("strength","closeness", "betweenness")` in the `plot()` command.

Best, Sacha
