### ISSUE TITLE
Error in differenceTest "object 'RA_Teased' not found"

### ISSUE THREAD

**Issue by etampke** [SachaEpskamp/bootnet#62]
Hi Dr. Epskamp, 

I am trying to use the bootnet differenceTest to evaluate significant differences in centrality indices. I was able to evaluate differences in Strength without any problems, but I am receiving an error message (i.e., "object 'RA_Teased' not found") when I try to evaluate closeness or betweenness. I can tell by the error that I must not have the proper node names entered.
 I don't understand why this would be happening given that my node names match my network graph and the output I received for my strength index (see attached)

#my initial bootstrapping evalution
TADbootCI3 <- bootnet(TeachAggData, type = c("nonparametric"), signed = TRUE,
                      memorysaver= TRUE, order = "sample")

#difference test comparing node closeness
TADclose <- differenceTest(TADbootCI3, RA_Teased, RA_Blames, "closeness")
>error: Error in differenceTest(TADbootCI3, RA_Teased, RA_Blames, "closeness") : 
  object 'RA_Teased' not found

#difference test comparing node strength(attached image, no errors):
plot(TADbootCI3, "strength")

<img width="1105" alt="Strenghth differenceTest" src="https://user-images.githubusercontent.com/78666780/107254660-226ad080-69fd-11eb-8474-8c75f09e3033.png">

**Comment by SachaEpskamp** [comment]
Your nodes are not characters, the command `differenceTest(TADbootCI3, RA_Teased, RA_Blames, "closeness")` looks for objects `RA_Teased` and `RA_Blames`, which you don't have. Instead, try `differenceTest(TADbootCI3, "RA_Teased", "RA_Blames", "closeness")`

**Comment by etampke** [comment]
> Your nodes are not characters, the command `differenceTest(TADbootCI3, RA_Teased, RA_Blames, "closeness")` looks for objects `RA_Teased` and `RA_Blames`, which you don't have. Instead, try `differenceTest(TADbootCI3, "RA_Teased", "RA_Blames", "closeness")`

I tried that as well and received this error:
differenceTest(TADbootCI3, "RA_Teased", "RA_Blames", "closeness")
 'x' is not a valid ID

**Comment by SachaEpskamp** [comment]
Right, you also have to include `"closeness"` in the `statistics` argument in `bootnet(...)`.

**Comment by etampke** [comment]
> Right, you also have to include `"closeness"` in the `statistics` argument in `bootnet(...)`.

Thank you so much! This resolved my issue!
