### ISSUE TITLE
bootstrap error

### ISSUE THREAD

**Issue by roxanajabbari** [SachaEpskamp/bootnet#63]
Hi,
I'm running bootstrapping for my network, but I receive this error:
in checkForRemoteErrors(val) : 
  one node produced an error: Maximum number of errors in bootstraps reached

Below are the codes that I ran. I should mention that I have 250 cases, 17 5-items likert ordinals without any missing data, and 3 continuos variables; one with 32 and another with 13 missing data:

Network2 <- estimateNetwork(data_full, default = "EBICglasso", corMethod = "cor_auto", missing="pairwise")
boot1a_PC <- bootnet(Network2, nBoots = 1000, nCores = 4) 
boot1b_PC <- bootnet(Network2, nBoots = 1000, type = "case",  nCores = 4,statistics = c("strength", "betweenness", "closeness")) 
I appreciate to help me to resolve this issue.

**Comment by SachaEpskamp** [comment]
You are likely returning too many errors in the analysis. With 5-point scales I would not use cor_auto, definitly not with only 250 cases. If you use `corMethod = "spearman"` you will likely get more stable results.

**Comment by roxanajabbari** [comment]
Thank you for your response.
I changed that and it worked.
In the latest workshop, you mentioned that if the ordinal variables have 5 or more, it is better to behave like a continuous variable. So this isn't a fixed rule, yes?

**Comment by SachaEpskamp** [comment]
It isn't a fixed rule. But 5 datapoints is usually fine, and the polychoric correlations seem to create more problems than they solve. See also https://psyarxiv.com/mbycn/.
