### ISSUE TITLE
cor_auto bootnet Error: Maximum number of errors in bootstraps reached

### ISSUE THREAD

**Issue by naburger** [SachaEpskamp/bootnet#64]
Hi!
I am estimating the accuracy of my networkmodel (with 17 ordinal variables) using the bootnet function, however some errors occur when I try to use corMethod 'cor_auto'.

      boot1 <- bootnet(Network1.1, nBoots = 1000, nCores = 8, 
                         statistics = c("edge", "strength", "closeness",
                                        "betweenness", "expectedInfluence"))

This works fine if I use an estimated network basen on corMethod = "cor":

      Network1.1 <- estimateNetwork(DATA1, corMethod = "cor", default = "EBICglasso")

However, if I use the cor_auto function within the estimateNetwork function an error occurs. 

      Network1 <- estimateNetwork(DATA1, corMethod = "cor_auto", corArgs = c(ordinalLevelMax = 9), default = "EBICglasso")

      Error in checkForRemoteErrors(val) : 
        one node produced an error: Maximum number of errors in bootstraps reached

Would you be able to help me with this?

**Comment by SachaEpskamp** [comment]
Hi, how many observations (rows in DATA1) do you have? the `cor_auto` method can be quite unstable especially at lower sample sizes, so overal I don't recommend using it anymore.

**Comment by naburger** [comment]
Thanks for your comment!

For two different networks I use 130 and 150 observations. Do you recommend using another method for ordinal data?

**Comment by SachaEpskamp** [comment]
Yes those are quite low sample sizes. I would use Spearman correlations (`corMethod = "spearman"`). See also https://psyarxiv.com/mbycn/.

**Comment by naburger** [comment]
Thank you very much!
