### ISSUE TITLE
sampleSize in estimateNetwork - docs vs code

### ISSUE THREAD

**Issue by falkcarl** [SachaEpskamp/bootnet#65]
Understood that `sampleSize` may be a bit of an ad-hoc solution when there is missing data and when doing EBICglasso. But, is there a mismatch between what is in the docs and what the code actually does?

The default (`pairwise_average`): "will set the sample size to the average of sample sizes used for each individual correlation."

The code in `sampleSize_pairwise` for this option does this:

`sampleSize <- mean(misMatrix)`

where `misMatrix` is a p x p matrix (p=number of variables) that contains counts of observations for each variable on the diagonal, and counts for each pairwise combination on the off-diagonals. Thus, `pairwise_average` counts the diagonal, not just the off-diagonal though more weight is given to the off-diagonal (above and below). Is that what is intended, and is it straightforward to even count the sample size for each individual correlation if what is estimated with EBICglasso are partial correlations?

Based on the docs, my first instinct was that the matrix of zero-order correlations is estimated first prior to being passed to the `glasso` package for estimation (assuming an appropriate way to handle missingness; that's a topic for another thread). And if so, then it'd seem that the sample size should only concern the average of off-diagonal elements in `misMatrix`. e.g.,

`sampleSize <- mean(misMatrix[lower.tri(misMatrix)])`

If this latter solution is what is intended, I can do a pull request from here (let's see if I can get cross-referencing to work): https://github.com/falkcarl/bootnet/commit/b0519ec2e48327b20f0439c01055982c65d51c10

If not, I would ask for more clarity in the docs.

**Comment by SachaEpskamp** [comment]
Hi,

Thanks for spotting this. I will look into this later to see what would be the best solution. The variances could also be considered part of the input, so this should also be an appropriate solution, but I agree that your proposed solution is probably better, so I will probably change that in a future version.

Best, Sacha

**Comment by falkcarl** [comment]
Hi Sacha,
A pull request was suggested by me in this issue (see previous exchange). If you are now open to a pull request given results here (https://osf.io/preprints/osf/dk6zv), please let me know and I will open it.
Thank you,
Carl
