### ISSUE TITLE
Measuring network closeness stability with isolated nodes

### ISSUE THREAD

**Issue by naburger** [SachaEpskamp/bootnet#66]
Hi!

I am checking the accuracy and stability of my estimated regularized (EBICglasso) network. One of the nodes is isolated and thus has a meaningless closeness score. When I plot the case dropping bootstrap in R using bootnet(), the closeness metric is not included in the plot. In the summary of the bootstraps, the closeness data is reported to be Not Available. I assume this is because of the isolated node. However, it remains strange that the closeness of the other nodes is also not available. Is it possible to exclude the isolated node from the bootstrap-evaluation? 

boot2.1 <- bootnet(Network1, nBoots = 1000, type = "case", nCores = 8,
                   statistics = c("edge", "strength", "closeness",
                                  "betweenness", "expectedInfluence"))

plot(boot2.1, statistics = c("strength", "closeness", "betweenness",
                             "expectedInfluence"))

I hope you can help me with this! 
Thankyou

**Comment by SachaEpskamp** [comment]
Hi,

Closeness is defined as the inverse of total distance from one node to every other node in the network, which is only defined if all nodes are connected. It is not possible in bootnet to drop a node from the computation.

Best, Sacha
