### ISSUE TITLE
Error: load package ‘bootnet’ due to vctrs package

### ISSUE THREAD

**Issue by NineEW** [SachaEpskamp/bootnet#68]
I have tried installing, updating and loading 'bootnet' and 'vctrs' but I keep getting the following error:

Error: package or namespace load failed for ‘bootnet’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘vctrs’ 0.3.4 is already loaded, but >= 0.3.5 is required

If I try to update 'vctrs' I get the following message:

package ‘vctrs’ successfully unpacked and MD5 sums checked
Warning in install.packages :
  cannot remove prior installation of package ‘vctrs’
Warning in install.packages :
  problem copying C:\Program Files\R\R-3.6.1\library\00LOCK\vctrs\libs\x64\vctrs.dll to C:\Program Files\R\R-3.6.1\library\vctrs\libs\x64\vctrs.dll: Permission denied
Warning in install.packages :
  restored ‘vctrs’

Any tips? Thanks!

**Comment by SachaEpskamp** [comment]
Hi,

You are using a very outdated version of R, which means that this type of backward compatibility cannot be guaranteed. Please update R and try to install the packages again.

Best, Sacha
