### ISSUE TITLE
Network Comparison Test

### ISSUE THREAD

**Issue by AdvaSegal** [SachaEpskamp/bootnet#7]
Hi,

What are the differences between "the network structure invariance", "the global strength invariance",  and "the edge invariance"?

Unfortunately, I didn't find papers that describe this issue in details. 

Thank you for your help.
Adva

**Comment by SachaEpskamp** [comment]
The network comparison test is not from the bootnet package. Please see https://github.com/cvborkulo/NetworkComparisonTest and https://www.researchgate.net/publication/314750838_Comparing_network_structures_on_three_aspects_A_permutation_test.

**Comment by AdvaSegal** [comment]
Thank you!
