### ISSUE TITLE
Network Edge-weights differ from correlation table

### ISSUE THREAD

**Issue by etampke** [SachaEpskamp/bootnet#70]
I am using Spearman correlation coefficients to estimate a network of symptoms of aggression using the Peer Conflict Scale (40 items; ordered categorical and skewed data). In the correlation table all of the association between items is positive, however when I use the same data to estimate networks, many edge weights are negative. Conceptually, I thought that networks were visual representations of coefficients, so I'm not sure why this would be happening.  I would greatly appreciate any help/explanation.

Here is my code: 
PRANetwork_Spear <- estimateNetwork(PCauto, default= "EBICglasso",
                              corMethod = "spearman", missing = "listwise", 
                              threshold = TRUE)
PRANetwork_Spear_plot <- plot(PRANetwork_Spear)

CorTable <- cor(PCauto, method = "spearman", use = "complete.obs")

(Note that there are only 2 participants with any missing data)

[CorTable.csv](https://github.com/SachaEpskamp/bootnet/files/6587448/CorTable.csv)
![Spearman Plot](https://user-images.githubusercontent.com/78666780/120553316-f618fc80-c3bd-11eb-87a5-970562870af0.png)

**Comment by SachaEpskamp** [comment]
With `default = "EBICglasso` you plot regularized partial correlations, not marginal correlations. See also our course materials at http://psychosystems.org/NetworkSchool.

Best, Sacha
