### ISSUE TITLE
Positive definite error despite spearman correlation

### ISSUE THREAD

**Issue by statsgirl1** [SachaEpskamp/bootnet#72]
Hi Sacha,

Thanks for creating this program. I recently got the error: 

Error in bootnet_correlate(data = data, corMethod = corMethod, corArgs = corArgs,  :
  Correlation matrix is not positive definite.
Calls: estimateNetwork -> do.call -> <Anonymous> -> bootnet_correlate

after running the code below: 

```
results <- estimateNetwork(datafile, default = "EBICglasso", corMethod = "cor", corArgs = list(method = "spearman"))
```

I saw your previous posts saying to use spearman correlation if I got a positive definite error and I tried that (as shown above) but I still get the error. Do you have any suggestions? The matrix is ~17000 x 17000. 

Thank you,
Helen

**Comment by SachaEpskamp** [comment]
Hi Helen,

The input to `estimateNetwork` should be raw data not a correlation matrix. So the input can't be a 17k by 17k matrix. 17k nodes is also far too many for the software to handle I think...

Best, Sacha
