### ISSUE TITLE
Bootnet error

### ISSUE THREAD

**Issue by pevitr** [SachaEpskamp/bootnet#74]
Hi,
I posted this earlier today, but realized I made the post on a "closed" issue, apologies for that.

I'm having an issue regarding bootnet. 
Currently running a network using a sample of ~730 youth.
The dataset is complete and items with no variability have been removed.

I am attempting to run bootnet for stability analyses but am getting the following error code when running my bootstrapping analyses:
"Error in checkForRemoteErrors(val) :
one node produced an error: Maximum number of errors in bootstraps reached"

Here is the code I have been using for network analyses.
mynames <- c("bully", "PhysFight", "Weapon", "CruelPpl", "CruelAni", "StolenVic", "Force",
"Fire", "Vandal", "Lie", "Shoplift", "Curfew")

Network<-estimateNetwork(MyDataCH.12, default = "EBICglasso", tuning = .5, labels = colnames(MyDataCH.12))

plot(Network, layout = "spring", vsize=6, color="lightblue", border.color="black",
nodeNames=mynames, legend=TRUE)

setwd("C:/Users/pevit/OneDrive/Pevitr/All Work & Research/UK/UK RISK Lab Research/Research Projects/Preschool_Childhood Projects/CD Network/Data/Excel/ChildhoodFull Y1")
pdf("Y1 ChildhoodFull CD_Network1.pdf")
myplot <- plot(Network, layout = "spring", vsize=6, color="lightblue", border.color="black")
dev.off()

library("NetworkToolbox")

b1 <- bootnet(Network, boots=1000, nCores = 4, statistics = c("strength", "expectedInfluence", "edge"))
b2 <- bootnet(Network, boots=1000, nCores = 4, type = "case", statistics = c("strength", "expectedInfluence", "edge"))

Again, running b1 or b2 leads to the error of "one node produced an error: Maximum # of erros in bootstraps reached"
Unsure if that "node" is referring to an actual item I have or something else. 

Thanks much!

**Comment by SachaEpskamp** [comment]
This error just means that in the multi-core process something goes wrong, but not what goes wrong. Try running it with `nCores = 1` which should give a more informative error.

**Comment by pevitr** [comment]
Thanks much for that feedback, that was helpful and was able to figure out the specific error in the code. Thank you!
