### ISSUE TITLE
opening bootnet

### ISSUE THREAD

**Issue by Wenhui-vivian** [SachaEpskamp/bootnet#78]
Hi!

I am new to bootnet and network analysis. I tried to launch bootnet but met errors. Please help and suggest solutions.
> library(bootnet)
Error: package or namespace load failed for ‘bootnet’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 object 'pkgInfo' not found
In addition: Warning messages:
1: package ‘bootnet’ was built under R version 4.2.0 
2: In loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) :
  package ‘zip’ has no 'package.rds' in Meta/

Thanks!

**Comment by SachaEpskamp** [comment]
Are you using the latest version of R and did you try re-installing the package?

**Comment by Wenhui-vivian** [comment]
Yes, I used the latest version of R and tried re-installing - neither of them worked.

**Comment by Wenhui-vivian** [comment]
I tried to reinstall zip but got these messages:

R version 4.1.1 (2021-08-10) -- "Kick Things"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Workspace loaded from ~/.RData]

> install.packages("zip", dep = TRUE)
WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
Installing package into ‘C:/Users/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/zip_2.2.0.zip'
Content type 'application/zip' length 1122176 bytes (1.1 MB)
downloaded 1.1 MB

package ‘zip’ successfully unpacked and MD5 sums checked
Warning in install.packages :
  cannot delete reparse point 'C:\Users\OneDrive\Documents\R\win-library\4.1/zip/Meta', reason 'There is a mismatch between the tag specified in the request and the tag present in the reparse point'
Warning in install.packages :
  cannot remove prior installation of package ‘zip’
Warning in install.packages :
  cannot delete reparse point 'C:\Users\OneDrive\Documents\R\win-library\4.1/zip/Meta', reason 'There is a mismatch between the tag specified in the request and the tag present in the reparse point'
Warning in install.packages :
  restored ‘zip’

The downloaded binary packages are in
	C:\Users\AppData\Local\Temp\RtmpSaYW26\downloaded_packages
> library(zip)
Error in library(zip) : ‘zip’ is not a valid installed package

Could you please help figure out the solution? Thanks!

**Comment by SachaEpskamp** [comment]
This seems to be related to some different package. You can try to install https://cran.r-project.org/bin/windows/Rtools/ perhaps to install that package? Or say no when asked to install anything from source.

**Comment by Wenhui-vivian** [comment]
Thanks for trying to help me. I figured that this issue was due to my Onedrive sync issue and it was solved when I unsync it.
