### ISSUE TITLE
Bootstrap error: Error in eigen(corMat) : infinite or missing values in 'x'

### ISSUE THREAD

**Issue by MalinRex** [SachaEpskamp/bootnet#79]
Hello Prof. Epskamp!

I run into the error code mentioned above when I try to estimate my network. 

When I run the following script:

_mynetwork <- estimateNetwork(inputdata, default = c("EBICglasso"), corMethod = "cor", corArgs =list (method = "spearman", use ="pairwise.complete.obs"))
boot1 <- bootnet(mynetwork, nBoots = 1000, nCores = 1, 
                 statistics = c("edge", "strength", "closeness",
                                "betweenness", "expectedInfluence"))_

I get this message: 

_Error in eigen(corMat) : infinite or missing values in 'x'
Error in bootnet(mynetwork, nBoots = 1000, nCores = 1, statistics = c("edge",  : 
  Maximum number of errors in bootstraps reached_

The data set (inputdata) is complete. It has many zeros, but no missing data. I see that many others have had similar issues, but were able to fix it by switching to Spearman correlation and setting nCores to 1. However, this doesn't seem to work in my case, and I am too new both to R and bootnet to be able to figure it out by myself.  Therefore, I'd be very grateful if you could point me in the right direction here!

Thanks!

**Comment by SachaEpskamp** [comment]
Hi Malin, what does the following command give?

    cor(inputdata, use = "pairwise.complete.obs")

Perhaps there are some linear dependencies or lack of variances in your data?

**Comment by MalinRex** [comment]
25 variables, 217 observations.

Below are the values I get when running the command:
 [1] 2.616 1.933 1.638 1.522 1.472 1.366 1.291 1.238 1.148 1.033 1.017 0.961 0.858 0.850 0.808 0.778 0.669 0.652 0.601
[20] 0.554 0.502 0.448 0.423 0.382 0.240

According to this, should I do any adjustments to my script?

**Comment by SachaEpskamp** [comment]
It could be that there are a few nodes with very low variance and/or very high correlations with other nodes, and removing these improves the estimation and bootstrapping.

**Comment by MalinRex** [comment]
OK, I see. Thank you for taking your time to guide me!
