### ISSUE TITLE
lambda.min.ratio

### ISSUE THREAD

**Issue by hautesh** [SachaEpskamp/bootnet#8]
I am getting a warning message when I run estimatenetwork that I should set my lambda.min.ratio lower. This is related to the long facebook conversation about large unstable network. I know I can use  lambda.min.ratio in qgraph, but when I try to use it in bootnet I get an error message.
Code: 
library(qgraph) 
library(bootnet) 
data <- read.table("C:/Users/Irina/Dropbox/EPSI Paper/EDEQ/Goldbricker/EDEQ1-1.csv", header=TRUE, sep=",")
n1 <- estimateNetwork(data,  lambda.min.ratio = 0.001, default="EBICglasso")
Error: 
Error in (function (data, tuning = 0.5, corMethod = c("cor_auto", "cov",  : 
  unused argument (lambda.min.ratio = 0.001)

**Comment by SachaEpskamp** [comment]
Do you use the Github version of bootnet?

> library("devtools")
> install_github("sachaepskamp/bootnet")

I think your codes should work then.

Best, Sacha
