### ISSUE TITLE
Length of communities argument does not match number of nodes" error

### ISSUE THREAD

**Issue by WivineBlekic** [SachaEpskamp/bootnet#84]
Hello, 

I'm sorry for what might be a beginner's mistake but it's starting to drive me crazy.

I'm trying to compute the bridge expected influence of a network of my own. Therefore, I followed the guidelines from  `networktools` along with some previous papers, but I'm stuck with this "Length of communities argument does not match number of nodes" error.
```
#Names and labels
Names_covar <- (scan("nodeNames2.txt", what = "character", sep = "\n"))
Labels_covar <- c("B1","B2", "B3", "B4", "B5", "C1", "C2", "D1", "D2", "D3", "D4", "D5", "D6", "D7", "E1", "E2", "E3", "E4", "E5", "E6", "MC","PS", "Hard", "AAQ")
Group3 <- c(rep("PTSD",20),rep('Clinical covariates', 4))

#Ploting bridge connections
Test <- estimateNetwork(data_covar, default="EBICglasso", corMethod="cor", corArgs=list(method="spearman", use="pairwise.complete.obs"))
Network <- plot(Test, title="Risky Behaviors and PTSD Clusters", groups=Group3, theme="colorblind", legend.cex=.32,  border.width=1.5, border.color="black", cut = 0)
c <- qgraph(Network, vsize=6.3, title = "", groups=Group3, legend.cex=.32, labels=Labels_covar, nodeNames= Names_covar, theme = "colorblind", border.width=1.5, border.color="black", cut = 0, layout = "spring", cut=0)
```
The network:
![Test](https://user-images.githubusercontent.com/95839793/145339809-c1e16920-2273-4a15-a6f3-c06a1ced7965.png)

```
#Trying to use the bridge function
group <-c (rep(1,20), rep(2,4)) #20 PTSD symptoms 4 covariates
c_b <- bridge(c, communities=group, directed=FALSE)
```
Everything runs (I attached the network and the file "nodeNames2"), except the last line "c_b <- `bridge`(c, communities=group, directed=FALSE)" which gives me the "Length of communities argument does not match number of nodes" error. I don't understand why considering that the networks has 24 nodes, and I describe 2 communities (one of 20 nodes and another one of 4 nodes).

I'm not sure if I could create a reproductible error without sending the data but I'll be happy to help and understand this error.

Thank you !

[nodeNames2.txt](https://github.com/SachaEpskamp/bootnet/files/7682478/nodeNames2.txt)

**Comment by SachaEpskamp** [comment]
I am not sure. Can you provide a reproducible example? E.g., the following works for me:

```
library("qgraph")
library("bootnet")
library("psychTools")
library("networktools")

net <- estimateNetwork(bfi[,1:25], default = "EBICglasso")
group <- c(rep(1,20),rep(2,5))
bridge(qgraph(net$graph), communities = group, directed=FALSE)

```

Please note that I did not write the `bridge` function, which is in the `networktools` package.

**Comment by WivineBlekic** [comment]
Hi, 
Thanks for your answer ! Turns out that the bridge function simply does not work with R version 4.1.1. With a previous version of R, it works without problem.

I'll send an email to the person in charge

Thanks again !

Wivine.

**Comment by SachaEpskamp** [comment]
Hi Wivine,

You should never use an outdated version of R though, as backward compatibility is pretty bad (there might be bugs introduced that have not been resolved).

Best, Sacha

**Comment by WivineBlekic** [comment]
Thanks for getting back to me,

I'll contact the person in charge of networktools, because a coworker of mine was able to run my code using the bridge function without problem, and the only difference is that he has a slightly previous version of R. If you're interested, I'll keep you in touch with this issue.

By the way, I read you new paper (meta-analysis of PTSD networks), it's really interesting ! Congratulation for this tremendous work. I'm submitting my own by the end of the month with the dataset I mentioned in my issue, and your paper gave more credibility to some methodological choices that I made for this network. Thanks for that and I hope to be among the firsts to quote your new paper! Honestly, without your papers and the video channel you made on network estimation, I wouldn't have been able to grab as quickly as I did the fundamentals of network estimation.

Best regards,

Wivine Blekić - PhD
Postdoctoral Fellow
Department of Emergency Medicine
Co​lumbia University Irving Medical Center
622 West, 168th Street
New York, NY 10032
[cid:283ca814-ffea-4a02-9312-09fa6cea5891]
________________________________
From: Sacha Epskamp ***@***.***>
Sent: Wednesday, December 15, 2021 10:59 AM
To: SachaEpskamp/bootnet ***@***.***>
Cc: Blekic, Wivine ***@***.***>; State change ***@***.***>
Subject: [EXTERNAL] Re: [SachaEpskamp/bootnet] Length of communities argument does not match number of nodes" error (Issue #84)


Hi Wivine,

You should never use an outdated version of R though, as backward compatibility is pretty bad (there might be bugs introduced that have not been resolved).

Best, Sacha

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_SachaEpskamp_bootnet_issues_84-23issuecomment-2D994928145&d=DwMCaQ&c=G2MiLlal7SXE3PeSnG8W6_JBU6FcdVjSsBSbw6gcR0U&r=0HjXnxCKwFBaDo5qtl2Dyf9chztJV-fkUQinfPHcmgA&m=mg9nKBf0k2P2LEfDTfBadJ6-1zS7PAEEhLvl-kXCAFk&s=y66MUdvPeC0YuC6bLuZfA56t4xOLWhnLwa7I2lOWZKw&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AW3GMMPUQELNWUKDRO6GXMLURC3OHANCNFSM5JVRGI2A&d=DwMCaQ&c=G2MiLlal7SXE3PeSnG8W6_JBU6FcdVjSsBSbw6gcR0U&r=0HjXnxCKwFBaDo5qtl2Dyf9chztJV-fkUQinfPHcmgA&m=mg9nKBf0k2P2LEfDTfBadJ6-1zS7PAEEhLvl-kXCAFk&s=0lgF7lsWe79YLHsFry_KYXrqrWTP29nzYsffkxwIYeM&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=G2MiLlal7SXE3PeSnG8W6_JBU6FcdVjSsBSbw6gcR0U&r=0HjXnxCKwFBaDo5qtl2Dyf9chztJV-fkUQinfPHcmgA&m=mg9nKBf0k2P2LEfDTfBadJ6-1zS7PAEEhLvl-kXCAFk&s=SiD4VPK1-UB2eNdRQQjA4R5w9VufOKa4n-MkiB_p3po&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=G2MiLlal7SXE3PeSnG8W6_JBU6FcdVjSsBSbw6gcR0U&r=0HjXnxCKwFBaDo5qtl2Dyf9chztJV-fkUQinfPHcmgA&m=mg9nKBf0k2P2LEfDTfBadJ6-1zS7PAEEhLvl-kXCAFk&s=JJuNrds-p-dEDhhbuO8EpPX7JMtS5gR0fzP3C_sV768&e=>.

**Comment by SachaEpskamp** [comment]
Dear Wivine,

Thank you very much for your very kind e-mail! And all the best in your
future work.

Best, Sacha

---
Sacha Epskamp
Assistant Professor
Department of Psychological Methods
University of Amsterdam
http://www.sachaepskamp.com
