### ISSUE TITLE
Maximum numbers of errors in bootnet

### ISSUE THREAD

**Issue by LauMalMur** [SachaEpskamp/bootnet#85]
Hi!

I have a problem when I do the bootnet analysis. It happens in 3 different networks I work with (an Ising, EBICGlasso and a mgm). 
The main problem is the appearance of the message
```
Error in checkForRemoteErrors(val) : 
  10 nodes produced errors; first error: Maximum number of errors in bootstraps reached
```
Part of my code is the following one
```
#Names and Labels
GDT_Names <- c("GDT1","GDT2","GDT3","GDT4")
GDT_Model <- gamblers[,c("GDT1","GDT2","GDT3","GDT4")]
GDT_Net <- estimateNetwork(GDT_Model,default = "EBICglasso")
ncores <- detectCores() -1
GDT_bootEA <- bootnet(GDT_Net,
                      nBoots = 1000,
                      nCores = ncores,
                      default = "IsingFit")

```
The message disappear if I don't use the nCores function...

**Comment by SachaEpskamp** [comment]
Did you try without `default = "IsingFit"` in the bootnet call? You are using a different estimator in `estimateNetwork.`

**Comment by LauMalMur** [comment]
Yes! I have 3 different models and all of them has the same problem.
I try it in another computer and it works, but I don't know how to fix it in my PC.
