### ISSUE TITLE
Plotting centrality stability showing only "strength" 

### ISSUE THREAD

**Issue by normscode0421** [SachaEpskamp/bootnet#88]
Hi Sacha and team, may I ask if you've ever encountered that in computing centrality stability using the "case" option for case dropping, that the plots only show "strength" and does not include "closeness" and "betweenness"? Grateful if you can help me troubleshoot this challenge.
<img width="1440" alt="Screenshot 2022-01-28 at 2 56 23 PM" src="https://user-images.githubusercontent.com/72509946/151501581-872fe182-66ed-4619-8185-bcad417d343f.png">

**Comment by SachaEpskamp** [comment]
You need to go explicitly request the other metrics using the `statistics` argument in `bootnet(...)`.

**Comment by normscode0421** [comment]
Thank you, Sacha. Appreciate your time. Sadly, the statistics argument, as below, still doesn't show closeness and betweenness:
boot2 <- bootnet(mynetwork, nBoots = 1000, nCores=4, type = "case")
plot(boot2, statistics = c("betweenness", "strength", "closeness"))

Am I doing it correctly? Thank you for your patience.

**Comment by normscode0421** [comment]
I've also tried statistics = "all", but also didn't plot the other stability scores. I'm getting the below warning:
<img width="563" alt="Screenshot 2022-01-28 at 8 39 53 PM" src="https://user-images.githubusercontent.com/72509946/151548532-4d746184-ecc9-4919-88b0-5769ed773c8b.png">

**Comment by SachaEpskamp** [comment]
You need to use the `statistics` argument in `bootnet(...)` as well.

**Comment by normscode0421** [comment]
Thanks, Sacha. It worked! Thank you for your prompt and patient response.
<img width="1425" alt="Screenshot 2022-01-28 at 11 35 54 PM" src="https://user-images.githubusercontent.com/72509946/151575820-a226b624-ae9f-4413-9d06-40078815c66e.png">

**Comment by normscode0421** [comment]
Thanks, Sacha. It worked! Thank you for your prompt and patient response.
<img width="1425" alt="Screenshot 2022-01-28 at 11 35 54 PM" src="https://user-images.githubusercontent.com/72509946/151575820-a226b624-ae9f-4413-9d06-40078815c66e.png">
