### ISSUE TITLE
Estimate group network bug?

### ISSUE THREAD

**Issue by Sara8419** [SachaEpskamp/bootnet#89]
Hello,

Hello,

Can someone help me with the code below? It runs, and then continuously runs, and then shuts down R. When I stop the command from continuously running in the console, it stops, but the code is not successfully completed.

Thank you! At a standstill at the moment.

EGN1 <- EstimateGroupNetwork(list(data1, data2), method="crossvalidation",
strategy="sequential", simplifyOutput = FALSE, seed=1337, ncores=8, covfun = cor_auto)

![6CAB24A8-C100-48B6-B370-8B7BB8083084](https://user-images.githubusercontent.com/102614085/160663986-d5aa88f6-fc46-46fb-955f-763f69b0f528.jpeg)
![73FF52E3-D41D-4A02-A045-A3F3CD675AF6](https://user-images.githubusercontent.com/102614085/160663988-947ad65b-e270-458f-be4b-99997797bdbb.jpeg)

**Comment by SachaEpskamp** [comment]
This is not a function from the bootnet package.
