### ISSUE TITLE
Extract confidence intervals 

### ISSUE THREAD

**Issue by lindoyle** [SachaEpskamp/bootnet#9]
Is there a way to extract the 5% and 95% confidence interval from the bootnet object? 
I have run
```
boot <- bootnet(data, default = "EBICglasso", type = "nonparametric", nBoots = 10)
plot(boot, labels = FALSE, order = "sample")
```
And then checked the output of all the different values that bootnet gives and I cannot find a way to extract just the confidence interval. 
Any suggestions would be great.

**Comment by SachaEpskamp** [comment]
You can obtain a table with `summary(boot)` (by default only the first 10 rows are printed).

**Comment by lindoyle** [comment]
Great, thanks!
