### ISSUE TITLE
Which bootstrapping default use with mgm?

### ISSUE THREAD

**Issue by WivineBlekic** [SachaEpskamp/bootnet#90]
Hello, 

I used the mgm function in `estimateNetwork` because I have a couple of binary items in my network

`Ntwk <- estimateNetwork(data_VarImp,
                         type = Type, 
                         level = Level,
                         default ='mgm', 
                         verbose = TRUE, 
                         criterion ="CV", 
                         nFolds = 10)`

Which runs super nicely, but I'm not sure about the type of bootstrapping method I need to use from here. I'm used to run 
`bootnet(data_VarImp, nBoots = 1000, default = "EBIC", type = "nonparametric")` but should I change the default to mgm or something else ? Everything runs fine with EBIC, but when I switch to mgm it loads for more than 2h but do not finish gets slower and slower and I just end up stopping it because it's surely not normal.

Do you have any insight for this issue?

Thank you, and I apologize if the question is a bit naive !

Wivine.

**Comment by SachaEpskamp** [comment]
Hi Wivine,

You just use the output from `estimateNetwork` as input to bootnet, which contains the estimator you chose:
`
bootnet(Ntwk, nBoots = 1000, type = "nonparametric")
`
