### ISSUE TITLE
edge weight bootstrap error

### ISSUE THREAD

**Issue by svnetwor** [SachaEpskamp/bootnet#91]
I'm trying to bootstrap the edge weight from an Ising network. I got the following message:
boot1 <- bootnet(Network, nBoots = 2000, nCores = 2)
Note: bootnet will store only the following statistics:  edge, strength, outStrength, inStrength
Error in data[, goodColumns, drop = FALSE] : 
  incorrect number of dimensions
In addition: Warning message:
In bootnet(Network, nBoots = 2000, nCores = 2) :
  Removing non-numeric columns: 3; 5; 6

I don't know how to resolve this. My data are binary and some variables have small variance (Warning messages:
1: In IsingFit(data, family = "binomial", gamma = 0.25) :
  Nodes with too little variance (not allowed): SSS16, SSS15, SSS9
2: In lognet(x, is.sparse, ix, jx, y, weights, offset, alpha, nobs,  :
  one multinomial or binomial class has fewer than 8  observations; dangerous ground). I suspect this is the cause of the bootstrap error, but I'm not sure.  

Any help will be appreciated!

**Comment by SachaEpskamp** [comment]
Hi, please make sure the input data only has numeric columns with zeroes and ones, and that you do not include columns that have only zeroes or only ones (too little variance).

**Comment by bethpeniel** [comment]
Dear Prof. Epskamp,
Thank you for the reply on the above issue. 

I do not have an error but I have "Note: bootnet will store only the following statistics: edge, strength, outStrength, inStrength"
Then my plot of bootnet gives me only Strength but not Betweenness and Closeness.

All my columns are numeric but not binary (0 and 1), they are continuous data, could this be the reason?
##
![boot1](https://user-images.githubusercontent.com/38100742/208062676-636a5765-5eb1-4051-9f6e-a351ab7df608.png)

boot1 <- bootnet(nt, nBoots = 2500, nCores = 8)
plot(boot1)

Plot is below:

**Comment by SachaEpskamp** [comment]
As the message says, closeness and betweenness are not stored or computed. You need to request this using the `statistics` argument in `bootnet(...)`.
