### ISSUE TITLE
HELP! Matrix not positive defined

### ISSUE THREAD

**Issue by Annalisa94** [SachaEpskamp/bootnet#94]
Hi,
I am trying to use simatenetwork with matrix (I checked, it is a matrix) of raw data using Ebicglasso. I get everytime the error that the matrix is not positive even if I followed your suggestion and I specify the cor method, even if I use spearman or kendall instead of Pearson, even if I set NoPostiveDefined= "continue". See an example attached.

N.B. I get the same error even if I use spearman. What can I do?
![IMG-20220708-WA0101](https://user-images.githubusercontent.com/74924101/178017785-592d0264-afa0-4baa-88cf-6de1c08ee03f.jpg)

Best regards,
Annalisa

**Comment by SachaEpskamp** [comment]
Dear Annalisa,

Is the object `DB_BD` a raw dataset containing only numeric values and nog e.g., a correlation matrix or a matrix with non-numeric columns? You also don't need to specify all the arguments that have default values (every argument in the manual that has a value listed there has a default you don't need to specify).

Best, Sacha

**Comment by Annalisa94** [comment]
Dear Sacha,

Thanks so much for the reply. Yes DB_BD is a raw dataset containing only numeric values. Even if I remove all the specification, I get the same error. What do I do?

Thanks,
Annalisa

**Comment by SachaEpskamp** [comment]
Dear Annalisa,

Can you show me a screenshot of what happens when you run `View(DB_BD)`?

Best, Sacha

**Comment by SachaEpskamp** [comment]
I will close this issue for now, but please let me know if you still run into problems.
