### ISSUE TITLE
Transforms corMethod = "npn" NAs into values?

### ISSUE THREAD

**Issue by JH2511** [SachaEpskamp/bootnet#96]
Hi Sacha,

I saw that you commented on this issue on the page for the huge package a while ago and they fixed it. I just wondered if you included that fix in bootnet, too? The output doesn't show how the data has been transformed.

Thank you,
Jan

**Comment by SachaEpskamp** [comment]
Hi Jan,

This still has not been fixed in the CRAN version of the huge package! 

```
df <- data.frame(a = c(1,5,4,2), b = c(NA,5,4,2))
library("huge")
huge.npn(df)
```

Do *not* use the nonparanormal transformation with `NA` values in your data, the results will be nonsensical.

**Comment by JH2511** [comment]
True, they fixed it in the github version, only. Yes,  I will not use it. Thanks for the response.
