### ISSUE TITLE
Questions about the function "bootnet_IsingFit" from bootnet ? 

### ISSUE THREAD

**Issue by Thnism** [SachaEpskamp/bootnet#98]
Hi Sacha,
I am sorry to ask some questions and want to know the estimation network of binary data. As we know, we have to estimate Ising model in the process of estimating estimation network of binary data. But as mentioned in the title, the function "bootnet_IsingFit" is a function from the package bootnet (thus, we can run the following code —— network <- bootnet::estimateNetwork(data,default = "IsingFit")) and there is another package IsingFit which can also achieve the estimating estimation network of binary data.
Thus, I would like to ask is there any difference between the function "bootnet_IsingFit" from bootnet and package IsingFit or is it right if I use the former package bootnet (network <- bootnet::estimateNetwork(data,default = "IsingFit"))) rather than the latter.

Thank you, Jane.

**Comment by SachaEpskamp** [comment]
Hi Jane,

The function `bootnet_IsingFit` is not intended for manual use and only documented to show what arguments can be used in `estimateNetwork(...)`. If you run:
`
network <- bootnet::estimateNetwork(data,default = "IsingFit")
`
Then under the hood the `bootnet_IsingFit` is called which in turn uses the IsingFit package to estimate the network model. I hope this clarifies!

Best,
Sacha

**Comment by Thnism** [comment]
Thank you for sparing your time to reply.  And best and sincere wishes.
