### ISSUE TITLE
Error with bootnet's bootstrapping

### ISSUE THREAD

**Issue by desphua** [SachaEpskamp/bootnet#99]
I get this error when I try to run bootstrap:
"Error in `dplyr::bind_rows()`:
! Can't combine `..1$node2` <integer> and `..2$node2` <character>."

My code is:
```
overall.bootstrap <- dataset %>% 
   bootnet(., nBoots = 1000, default="ggmModSelect", computeCentrality = TRUE, nCores=8,
   statistics=c("edge", "strength"), labels=c(seq(1:50)), model="GGM", corMethod="spearman")
```

**Comment by SachaEpskamp** [comment]
Hi! First try to run this with `estimateNetwork` to see if it works. `bootnet()` is designed to take the output from `estimateNetwork` as input:

```
net <- estimateNetwork(dataset , default = "ggmModSelect", corMethod="spearman")
plot(net)
overall.bootstrap <- bootnet(net , nBoots = 1000, nCores=8, statistics=c("edge", "strength"))
```

**Comment by SachaEpskamp** [comment]
I will close this issue for now but please let me know if you still run into problems.
